core/src/main/java/org/kestra/core/queues/QueueException.java
core/src/main/java/org/kestra/core/queues/QueueInterface.java
core/src/main/java/org/kestra/core/runners/Worker.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutor.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaQueue.java
runner-kafka/src/main/java/org/kestra/runner/kafka/services/KafkaAdminService.java
runner-kafka/src/main/java/org/kestra/runner/kafka/services/KafkaConsumerService.java
runner-kafka/src/main/java/org/kestra/runner/kafka/services/KafkaProducerService.java
runner-kafka/src/main/java/org/kestra/runner/kafka/services/KafkaStreamService.java
runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java

If an emit failed, before the error was silenced and the thread is removed silently.
Now, we try the save mark the WorkerTask has failed and if we can't we just kill the application

fix(runner-kafka): handle queue emit exception

---

ui/src/components/flows/FlowEdit.vue

Related to R01:
> Lorsque l'on clique sur Add flow, le focus n'est pas mis
> dans l'éditeur par défaut. Il faut donc cliquer dans
> l'éditeur pour pouvoir coller notre yaml.

fix(ui): autofocus in the textarea

---

storage-local/src/main/java/org/kestra/storage/local/LocalStorage.java

Hello,
As I know, mkdir could return false by security reason, so it seems better to throw exception when it has failed to create directory.
If there is misunderstanding, please let me know 🙏

Check if mkdir succeed or not

---

core/src/main/java/org/kestra/core/runners/AbstractExecutor.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutor.java
runner-kafka/src/main/java/org/kestra/runner/kafka/streams/ExecutionNextsDeduplicationTransformer.java
runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java
runner-memory/src/main/java/org/kestra/runner/memory/MemoryExecutor.java

On high concurrency, some WorkerTasK can be send multiple time led to error Can't find taskRun.
We need to add a deduplication and flatten the KafkaStream tree for KafkaExecutor.

fix possible duplicate workerTask submitted

---

ui/src/components/executions/Executions.vue
ui/src/components/flows/Flows.vue

fix(ui): prevent chart to load when data are not ready

---

core/src/main/java/org/kestra/core/docs/DocumentationGenerator.java
core/src/main/java/org/kestra/core/models/triggers/PollingTriggerInterface.java
core/src/main/java/org/kestra/core/models/triggers/types/Schedule.java
core/src/main/java/org/kestra/core/plugins/PluginRegistry.java
core/src/main/java/org/kestra/core/plugins/PluginScanner.java
core/src/main/java/org/kestra/core/plugins/RegisteredPlugin.java
core/src/main/java/org/kestra/core/runners/RunContext.java
core/src/main/java/org/kestra/core/runners/RunContextFactory.java
core/src/main/java/org/kestra/core/schedulers/Scheduler.java
core/src/main/java/org/kestra/core/schedulers/SchedulerExecutionWithTrigger.java
core/src/main/java/org/kestra/core/storages/StorageInterface.java
core/src/main/java/org/kestra/core/utils/ExecutorsUtils.java
core/src/main/java/org/kestra/core/utils/TestsUtils.java
core/src/test/java/org/kestra/core/models/triggers/types/ScheduleTest.java
core/src/test/java/org/kestra/core/schedulers/AbstractSchedulerTest.java
core/src/test/java/org/kestra/core/schedulers/SchedulerScheduleTest.java
core/src/test/java/org/kestra/core/schedulers/SchedulerThreadTest.java
webserver/src/main/java/org/kestra/webserver/controllers/PluginController.java

PollingTrigger will be handle by a dedicted poll in order to support long running Trigger
We also honor the `interval` parameters in order to control the frequency of the test

feat(core): handle PollingTrigger in a dedicated pool

---

core/src/main/java/org/kestra/core/models/executions/NextTaskRun.java
core/src/main/java/org/kestra/core/models/tasks/FlowableTask.java
core/src/main/java/org/kestra/core/models/tasks/ResolvedTask.java
core/src/main/java/org/kestra/core/models/triggers/AbstractTrigger.java
core/src/main/java/org/kestra/core/runners/AbstractExecutor.java
core/src/main/java/org/kestra/core/runners/FlowableUtils.java
core/src/main/java/org/kestra/core/runners/RunContext.java
core/src/main/java/org/kestra/core/tasks/flows/EachParallel.java
core/src/main/java/org/kestra/core/tasks/flows/EachSequential.java
core/src/main/java/org/kestra/core/tasks/flows/Parallel.java
core/src/main/java/org/kestra/core/tasks/flows/Sequential.java
core/src/main/java/org/kestra/core/tasks/flows/Switch.java
core/src/main/java/org/kestra/core/tasks/flows/Template.java
core/src/main/java/org/kestra/core/utils/Await.java
core/src/test/java/org/kestra/core/tasks/flows/TemplateTest.java
core/src/test/resources/flows/valids/with-template.yaml

Later the outputs are save later and unusable for childs tasks.
Also add input on template to rename a vars on a template and don't depend on global context

feat(core): save Flowable output at taskRun creation

---

core/src/main/java/org/kestra/core/models/flows/Flow.java
core/src/main/java/org/kestra/core/repositories/FlowRepositoryInterface.java
core/src/main/java/org/kestra/core/services/FlowService.java
core/src/test/java/org/kestra/core/runners/FlowListenersTest.java
core/src/test/java/org/kestra/core/schedulers/AbstractSchedulerTest.java
core/src/test/java/org/kestra/core/schedulers/SchedulerScheduleTest.java
core/src/test/java/org/kestra/core/schedulers/SchedulerThreadTest.java
core/src/test/java/org/kestra/core/services/FlowServiceTest.java
repository-elasticsearch/src/main/java/org/kestra/repository/elasticsearch/ElasticSearchFlowRepository.java
repository-memory/src/main/java/org/kestra/repository/memory/MemoryFlowRepository.java
runner-kafka/build.gradle
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaFlowListeners.java
runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaFlowListenersTest.java
runner-memory/src/main/java/org/kestra/runner/memory/MemoryFlowListeners.java
runner-memory/src/test/java/org/kestra/runner/memory/MemoryFlowListenersTest.java

Now scheduler can be scalable and deploy as many time as you want.
We use kafka to dispatch flow between different scheduler.

feat(core): make scheduler scalable

---

ui/src/components/executions/Executions.vue

so the execution are always sorted by default now

fix(ui): set execution default sort when all the logic does not provide sort information in route

---

core/src/main/java/org/kestra/core/queues/QueueFactoryInterface.java
core/src/test/java/org/kestra/core/Helpers.java
core/src/test/resources/flows/valids/inputs-large.yaml
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutor.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutorProductionExceptionHandler.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaQueue.java
runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaQueueFactory.java
runner-kafka/src/main/java/org/kestra/runner/kafka/services/KafkaStreamService.java
runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaQueueTest.java
runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java
runner-memory/src/main/java/org/kestra/runner/memory/MemoryQueueFactory.java

if kafka message is over `max.request.size` this will failed the executor until message is skipped.
we try to send a failed execution and continue the stream

fix(kafka-runner): handle large messsage exception

---

README.md

For some reason the bottom link pointed to the [NocoDB](https://www.nocodb.com/) Discord server.

Fix Discord server link

---

docker-compose.yml

I got that error ` FATAL:  role "root" does not exist ` by some searching, i got that possible generic solution. So, may we consider changing that?
Issue #628

Fix - FATAL:  role "root" does not exist

---

core/src/main/java/io/kestra/core/models/templates/Template.java
ui/src/components/templates/Templates.vue
webserver/src/test/java/io/kestra/webserver/controllers/TemplateControllerTest.java

Kestra do not support description for template.
Added the property in the Template model, then add test to verify the description is well handled
https://github.com/kestra-io/kestra/issues/721
close #721

Feat(Template model): Added description to template

---

ui/src/components/graph/TreeNode.vue
ui/src/components/layout/MarkdownTooltip.vue

- In the topology view, clicking on the button would not work, it was required to click on the icon.

Fixing Vue 3 issues

---

docker-compose-ci.yml
docker-compose-ha.yml

Both Apache Zookeeper and Kafka checks cluttered the logs.
* Zookeeper complained about the immediate connection close.
* Kafka couldn't recognize the sequence.

Use nonintrusive health checks

---

core/src/main/java/io/kestra/core/tasks/scripts/runners/DockerScriptRunner.java

Use the default random Docker container name.
Also improve handling of failed containers and potential Java exceptions.
I move out of the try-with-resource the Docker commands, I check the source, there close method is empty, by this the code is clearer.
close #948

Use a random name for the Docker container

---

core/src/main/java/io/kestra/core/models/executions/Execution.java
core/src/main/java/io/kestra/core/models/executions/TaskRun.java
core/src/main/java/io/kestra/core/models/flows/State.java
core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/main/java/io/kestra/core/schedulers/DefaultScheduler.java
core/src/main/java/io/kestra/core/services/ConditionService.java
core/src/main/java/io/kestra/core/services/ExecutionService.java
core/src/test/java/io/kestra/core/runners/ListenersTestTask.java
core/src/test/java/io/kestra/core/runners/WorkerTest.java
core/src/test/java/io/kestra/core/tasks/flows/FlowCaseTest.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcScheduler.java
runner-kafka/src/main/java/io/kestra/runner/kafka/executors/ExecutorMain.java
runner-kafka/src/main/java/io/kestra/runner/kafka/streams/ExecutorJoinerTransformer.java
runner-kafka/src/main/java/io/kestra/runner/kafka/streams/ExecutorKilledJoinerTransformer.java
runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java

fix(core): typo isTerminated

---

ui/src/components/flows/FlowRun.vue

Pressing  `enter` in the flowRun component now trigger the execution.
To keep possibility to add newline in text-area form use for JSON, the shortcut `shit + enter` is now available to creating newline
close #903

feat(FlowRun): Enter key validate inputs form and trigger the execution

---

ui/src/components/executions/Topology.vue
ui/src/components/flows/TaskEdit.vue
ui/src/components/graph/Topology.vue
ui/src/components/graph/TreeNode.vue
ui/src/components/graph/nodes/Task.vue
ui/src/components/logs/LogList.vue
ui/src/stores/flow.js
ui/src/translations.json
webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java

Task source code is now read only in the execution logs tab.
If the execution is from an old revision, warn the user and display the revision number
close #928

Feat(UI/Execution): Read only task source in logs 

---

core/src/main/java/io/kestra/core/docs/PluginDocumentation.java

Should resolves the issue with task links in https://kestra.io/plugins/plugin-azure/

fix: subgroup potentially has a '.' in its name

---

core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java
core/src/main/java/io/kestra/core/models/triggers/types/Flow.java
core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java
core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java
core/src/main/java/io/kestra/core/plugins/PluginScanner.java
core/src/main/java/io/kestra/core/tasks/flows/Template.java
core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java
webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java

Multiple doc improvements:
- Don't transform `@JsonType` as they procudes stange documentation like https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.Copy.html#retryauto
- Add missing `@PluginProperty` on trigers
- Add a `@Schema(defaultValue="...")` on the WebHook trigger to mask the generated ID from the documentation
- Don't register plugin classes that have the `@Hidden` annotation, this annotation is also added to the `Template$ExecutorTemplate` class.
- Enable MAP_VALUES_AS_ADDITIONAL_PROPERTIES  so that for Map properties, the value type is automatically registered as additionalProperties inside the JSON Schema.
Fixes #970

Improve doc

---

core/src/main/java/io/kestra/core/services/FlowService.java

Very small PR to indicate that multiple-condition is optional.
This method will be used with null multiple-condition storage from the Kafka runner.

feat(core): allow listing trigger without multiple conditions

---

cli/src/main/resources/application.yml
jdbc-postgres/src/main/resources/migrations/postgres/V6__queue_index_optim.sql

Improve JDBC performance by lowering the min poll loop interval and changing PostgreSQL indexing.
Min poll loop interval is the minimum delay between each task execution. When running a single flow that have a lot of tasks, lowering it lower the delay between each tasks. It is currently configured at 100ms, configuring it to 25ms show a nice performance gain and should still be not too low so the database will not be sollicited too much. See performance gains bellow.
On PostgreSQL, the `queues` table unique index disturb the PostgreSQL cost optimizer that chooses this index when doing the poll query resulting in 10ms poll queries on a table with a few thousands of line.
Removing the PK and the index that exists on the columns type and offset, and replacing them with a hash index on the …

Improve jdbc performance

---

docker-compose.yml

Postgres will be ready after the first health check wich is after 30s! We can starts Kestra as soon as Postgres is started.
An other solution would be to lower the Postgres health check interval.

feat(docker): don't wait for Postgres to be ready before starting Kestra

---

docker-compose-ha.yml
docker-compose.yml

The runtime presents both 8080/tcp and 8081/tcp. Both should be accessible.

Publish the monitoring endpoint

---

core/src/main/java/io/kestra/core/models/flows/Flow.java
core/src/main/java/io/kestra/core/services/ExecutionService.java
core/src/test/java/io/kestra/core/Helpers.java
core/src/test/java/io/kestra/core/runners/RestartCaseTest.java
core/src/test/java/io/kestra/core/runners/RestartTest.java
core/src/test/resources/flows/valids/restart_always_failed.yaml
core/src/test/resources/flows/valids/restart_local_errors.yaml
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java

As they else they will run un-conditionnaly and the flow will be SUCCESSFUL
close #1032

fix(#1032):  avoid restarting errors task

---

core/src/main/java/io/kestra/core/models/executions/Execution.java
core/src/main/java/io/kestra/core/models/flows/State.java
core/src/main/java/io/kestra/core/runners/Executor.java
core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/main/java/io/kestra/core/runners/FlowableUtils.java
core/src/main/java/io/kestra/core/runners/RunnerUtils.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/main/java/io/kestra/core/services/ExecutionService.java
core/src/main/java/io/kestra/core/tasks/flows/Flow.java
core/src/test/java/io/kestra/core/tasks/flows/PauseTest.java
core/src/test/resources/flows/valids/pause-delay.yaml
core/src/test/resources/flows/valids/pause.yaml
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java
ui/src/components/executions/ChangeStatus.vue
ui/src/components/logs/LogList.vue
ui/src/utils/state.js

Fixes #1103
Fixes #1114
@yuri1969 I tested 10k flow executions and all ends up green with this patch so I think it will fix #1114.
My test flow is:
```yaml
id: wait-and-delay
namespace: io.kestra.tests
tasks:
- id: wait-and-resume
type: io.kestra.core.tasks.flows.Pause
description: "Wait 10 sec and then resume"
delay: PT10S
tasks:
- id: hello-world
message: Hello World
```
As soon as this PR is merged this would be great if you can test it and assert your issues are fixed.

fix(core,ui) Pause task

---

ui/src/components/flows/FlowRun.vue
ui/src/styles/layout/element-plus-overload.scss

Slightly longer input variable names caused overflow at a lowend 1600x900px display.
This is a simple hotfix.
Before:
After:

Adapt the inputs names within 'New execution'

---

ui/src/components/inputs/Editor.vue

Had to use `window.innerWidth` since the editor component does not allow use of Element-plus grid

feat(UI): hide documentation if screen res is too low

---

core/src/main/java/io/kestra/core/serializers/FileSerde.java
core/src/main/java/io/kestra/core/tasks/storages/Concat.java
ui/src/utils/utils.js

Currently, when a row is null it is written as the "null" string instead as a null / empty line.
This fixes the issue and also fix a small UI bug when a null file results in a "NaN Kb" in the output tab.

fix(core): Serialize null as null and not "null" in the ION file

---

ui/src/components/graph/Topology.vue

At creation, we do not know the final namespace, so we should let the user edit everything.

fix: Allow topo edition when creating

---

ui/src/components/executions/Executions.vue
ui/src/components/flows/Flows.vue

Actual conditions required to be Kestra Admin to display `Select` in executions and flow list, which makes nonsense.
I removed conditions and let the backend handle it because we can't check for every row if the user has the right access.

fix(): Removed front access verification

---

ui/src/components/flows/TaskEditor.vue
ui/src/stores/plugins.js

This PR fixes a conflict between this PR https://github.com/kestra-io/kestra/pull/1294 and this one https://github.com/kestra-io/kestra/pull/1229, as @loicmathieu noticed.
The issue is that we cannot set `all=true` by default because it brings all the task default properties to each task definition in the documentation, making the documentation noisier (especially in tasks like the [Bash](https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.bash#properties) one which already have a lot of properties).
But on the other side, we need those properties for the low-code form.
So to avoid duplicate code, as the only difference is a param in the URL, I store the result in a different state variable depending if the param was given or not.
Note that the new variable …

fix(core): fix plugin definition conflict

---

ui/src/stores/flow.js

Fix an issue where first arriving on the homepage lead to the welcome page as `overallTotal` was set to 0 by default.

fix(core): Fix bad redirection on homepage

---

core/src/main/java/io/kestra/core/tasks/flows/If.java

The validation calls `allChildTasks()` so it must works with a null then for the validation to return errors and not fail with an exception (status code 422 instead of 500).
close #1309

fix(core): avoid validation exception when the then property is nul

---

core/src/main/resources/docs/task.hbs

close [#1255](https://github.com/kestra-io/kestra/issues/1255)
Note that for the example given in the issue additionalProperties is not needed as the JsonSchemaGenerator correctly read generic parameters so it leads to two times the same type (better than a bug in the doc). additionalProperties usage should be carefully reviewed to discover such duplications.

fix(core): correctly display additional properties in documentation

---

core/src/main/java/io/kestra/core/repositories/MetricRepositoryInterface.java
core/src/test/java/io/kestra/core/repositories/AbstractMetricRepositoryTest.java
jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcMetricRepository.java
repository-memory/src/main/java/io/kestra/repository/memory/MemoryMetricRepository.java
ui/src/components/flows/FlowMetrics.vue
ui/src/stores/flow.js
webserver/src/main/java/io/kestra/webserver/controllers/MetricController.java

Shame on me for doing it the lazy way. Now we correctly query all tasks that have metrics, including deleted ones.
close #1297

fix(webserver): Query distinct task that have metrics

---

ui/src/components/graph/Topology.vue
webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java

Currently, we validate the flow before generating the graph of the topology. However, this validation doesn't make sense because the graph generation process only requires the task's ID and type, not the task properties.
https://github.com/kestra-io/kestra/blob/dbd7725bea3e154d59e9670b7f281bd6e160a5db/webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java#L100
On the UI side, we have a flow validation that will bring errors to the users [using the /validate endpoints](https://github.com/kestra-io/kestra/blob/dbd7725bea3e154d59e9670b7f281bd6e160a5db/webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java#L443). So validation properties in graph generation does not bring anything to the frontend.
It even reduces user experience because any error on a …

Suggestion :  Remove fields validation from DAG generation

---

core/src/main/java/io/kestra/core/runners/ExecutorService.java

This should be an improvement as created tasks will go to the killed state earlier.

feat(core): kill created tasks earlier

---

core/src/main/java/io/kestra/core/models/flows/input/FileInput.java
core/src/test/java/io/kestra/core/runners/InputsTest.java
core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java
core/src/test/resources/flows/valids/inputs.yaml

Due to the way we upload them, it's not possible to validate the FILE input as we didn't have the file name.

fix(core): remove input FILE validation

---

ui/src/components/inputs/Editor.vue

This call was used when task documentation was integrated into the editor component.
close #1349

fix(ui): Remove useless API call

---

ui/src/components/flows/TaskEdit.vue
ui/src/components/flows/TaskEditor.vue
ui/src/components/flows/tasks/TaskCondition.vue
ui/src/components/flows/tasks/TaskTask.vue
ui/src/components/graph/Topology.vue
ui/src/components/graph/TreeTaskNode.vue
ui/src/components/graph/TreeTriggerNode.vue
ui/src/components/graph/nodes/Edge.vue
ui/src/components/logs/LogList.vue
ui/src/components/plugins/PluginSelect.vue
ui/src/stores/flow.js
ui/src/utils/constants.js
ui/src/utils/yamlUtils.js
webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java

fix(ui): validation of trigger on lowcode failed

---

ui/src/components/graph/Topology.vue

* Added a new item representing the chosen Editor visual style to the local storage.
* Enabled persisting the editor width even on regular component removal.
close #1411

Keep the Editor preference persisted

---

.github/workflows/main.yml
.gitpod.yml
gradle.properties

Set Gradle defaults to _common_ ones. Any of them should be safe to use with Gradle 8.
* Subprojects are built in parallel when possible.
* Task outputs can be reused.
* Gradle processes get deprioritized - keeping your machine responsive.

Tune Gradle defaults

---

ui/src/components/executions/Executions.vue
ui/src/components/executions/Overview.vue
ui/src/components/home/HomeSummaryFailed.vue
ui/src/components/layout/Labels.vue

* Execution labels are presented at both execution list and overview.
* Filtering 'by the label' works for both flow and execution list.
* An active 'by the label' filter can be deactivated by clicking at the label again.
* Labels being a part of the active filter are highlighted.
Related to #1527

Show execution labels

---

ui/src/components/executions/Executions.vue
ui/src/components/flows/Flows.vue
ui/src/components/labels/LabelFilter.vue
ui/src/translations.json

The execution listing view can be filtered by multiple execution labels.
This is based on the existing backend functionality built as #1190.
This is more or less just a design proposition - I'm no UI/UX designer so this tag-based attempt most probably doesn't perfectly fit to the overall feel.
close #1308

Filter executions by labels

---

ui/src/components/home/Home.vue

It seems that going from the execution details pages to the flow details pages, Home component is not updated correctly, when mounted and created are called, it's still the previous data. Watching  the flowId property fix the issue.
Issue not faced in the namespace detail page (that use the same Home component)
close #1468

fix(ui): Flow Overview is refreshed correctly

---

ui/src/components/onboarding/VueTour.vue

So the next step doesnt appear before the flow is saved and get out of scope.
close #1464

fix(ui): slightly increase timeout before next step when saving guided tour flow

---

core/src/main/java/io/kestra/core/models/triggers/types/Flow.java
core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java
core/src/main/java/io/kestra/core/runners/RunnerUtils.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/models/triggers/types/FlowTest.java
core/src/test/java/io/kestra/core/models/triggers/types/ScheduleTest.java
core/src/test/java/io/kestra/core/schedulers/AbstractSchedulerTest.java
core/src/test/java/io/kestra/core/schedulers/SchedulerThreadTest.java
core/src/test/resources/flows/valids/inputs.yaml
core/src/test/resources/flows/valids/webhook.yaml
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java

close [#1325](https://github.com/kestra-io/kestra/issues/1325)
Only polling triggers will not push flow labels to execution labels, as they are totally refactored in the poll trigger on worker PR this must be evaluated later if it can be done for all polling triggers. I'll create an issue for that.

feat: add flow labels to execution labels

---

core/src/main/java/io/kestra/core/schedulers/DefaultScheduler.java
runner-memory/src/main/java/io/kestra/runner/memory/MemorySchedulerTriggerState.java

This should improve tests:
- Wait for a trigger when we receive an execution with a trigger to avoid possible race between the triggerQueue and the executionQueue
- Use the condition service to be sure that an execution is terminated
- Make the memory trigger state `findLast` atomic

fix(core): improve memory scheduler

---

core/src/test/java/io/kestra/core/schedulers/SchedulerConditionTest.java
ui/src/components/flows/FlowRun.vue
ui/src/components/labels/LabelInput.vue
ui/src/translations.json

New label input when starting a new execution :
That is more close to the label edition in a flow :
Which also cover bad values : 
When both key & value are empty, we just ignore them : 
close #1630

fix(ui): better label input

---

ui/src/components/labels/LabelFilter.vue

Usage of the filter often led to HTTP 500 - enabled basic input validation.
Fixed misc minor type-related issues.

Validate the label filter input

---

README.md

This pull request resolves the issue #1682. The changes in this commit fixes typos in the links to 6 Plugins (Bash, Groovy, Jython, Nashorn, Node, Python) available on the README.

Update README.md - close #1682

---

core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java

This is not the real default that is on the implementation. Unfortunately, the documentation display this default value instead of the real one.

fix(core): remove misleading default value for polling triggers

---

core/src/main/java/io/kestra/core/tasks/flows/WorkingDirectory.java
ui/src/translations.json

(docs) Add more context to the `WorkingDirectory` and change Api to API

---

core/src/main/java/io/kestra/core/metrics/MetricRegistry.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java
core/src/test/java/io/kestra/core/runners/RetryTest.java

Fixes https://github.com/kestra-io/kestra-ee/issues/318

fix(core): add worker group tag to the metrics

---

core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/test/java/io/kestra/core/tasks/flows/BadFlowableTest.java
core/src/test/java/io/kestra/core/tasks/flows/TemplateTest.java
core/src/test/resources/flows/valids/flowable-with-parent-fail.yaml

Fixes #1745
In the executor, when a flowable task throw an exception when calling `resolveNexts()` this will fail the current evaluation of the executor that will be retried indefinitly. Catching exception and returing an empty next will avoid the infinite loop and the task will fail properly.

fix(core): avoid infinite loop in the executor for Flowable tasks

---

jdbc/src/test/java/io/kestra/jdbc/JdbcTestUtils.java

This is 4.5x quicker for MySQL and 2x for Postgres

chore: delete all instead of truncate in tests

---

ui/src/styles/layout/root-dark.scss

For instance, input description was unreadable.
Feel free to tune the color according to UX rules.

Make the Dark theme's `.text-muted` visible

---

core/src/main/java/io/kestra/core/serializers/JacksonMapper.java

So setting it two times will override the previous one.

fix(core): serialization inclusion is a single property not a list

---

README.md
core/src/main/java/io/kestra/core/tasks/scripts/AbstractBash.java
core/src/main/java/io/kestra/core/tasks/scripts/AbstractLogThread.java
core/src/main/java/io/kestra/core/tasks/scripts/AbstractPython.java
core/src/main/java/io/kestra/core/tasks/scripts/Bash.java
core/src/main/java/io/kestra/core/tasks/scripts/BashService.java
core/src/main/java/io/kestra/core/tasks/scripts/Node.java
core/src/main/java/io/kestra/core/tasks/scripts/Python.java
core/src/main/java/io/kestra/core/tasks/scripts/RunResult.java
core/src/main/java/io/kestra/core/tasks/scripts/ScriptOutput.java
core/src/main/java/io/kestra/core/tasks/scripts/runners/DockerScriptRunner.java
core/src/main/java/io/kestra/core/tasks/scripts/runners/ProcessBuilderScriptRunner.java
core/src/main/java/io/kestra/core/tasks/scripts/runners/ScriptRunnerInterface.java
core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java
core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java
core/src/test/java/io/kestra/core/models/flows/FlowWithSourceTest.java
core/src/test/java/io/kestra/core/repositories/AbstractFlowRepositoryTest.java
core/src/test/java/io/kestra/core/runners/WorkerTest.java
core/src/test/java/io/kestra/core/tasks/flows/TimeoutTest.java
core/src/test/java/io/kestra/core/tasks/test/Sleep.java
webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java

Only their own tests still use them.
But flow tests use them A LOT in the flow YAML definitions!

feat(core): deprecate old script tasks and stop using them in tests

---

ui/src/components/executions/VarValue.vue

feat(UI): Change output link for button + add space between number and 'download'

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/test/java/io/kestra/core/runners/RunContextTest.java

This will be used in tasks that download a file and want to preserve the extension.

feat(core): add a method to help getting a file extension

---

jdbc/src/main/java/io/kestra/jdbc/JooqExecuteListenerFactory.java

Directly create a new ExecuteListener as the DefaultExecuteListener is deprecated and does nothing.

fix: remove deprecated

---

ui/src/components/flows/FlowRun.vue
ui/src/components/layout/Markdown.vue

The input `description` field is [meant to hold Markdown](https://kestra.io/docs/developer-guide/inputs#input-properties).

Render flow input description

---

jdbc-postgres/src/main/resources/migrations/postgres/V19__index_execution-labels.sql

This can only be done on Postgres:
- H2 didn't support index on JSON array
- MySQL only support index on JSON array of scalar values not JSON array of objects
close #1307
WARNING: if #1845 is merged before the migration must be renamed

feat(jdbc): add an index on the execution labels

---

jdbc-h2/src/main/resources/migrations/h2/V18_index_logs.sql
jdbc-mysql/src/main/resources/migrations/mysql/V16_index_logs.sql
jdbc-postgres/src/main/resources/migrations/postgres/V21_index_logs.sql

Without this new index, the index on timestamp is always used. 
Fixes #1810

feat: improve logs indexes

---

core/src/main/java/io/kestra/core/models/flows/Input.java

This has no strong consequences but allow to set validation for a string input in a boolean input

fix: BOOLEAN input should use BooleanInput and not StringInput

---

ui/src/components/layout/Environment.vue
ui/src/components/settings/Settings.vue
ui/src/override/components/LeftMenu.vue
ui/src/stores/layout.js
ui/src/translations.json
webserver/src/main/java/io/kestra/webserver/controllers/MiscController.java

Added env name + color settings to set local user-specific labels.
close #1483

Label Kestra environments

---

cli/src/main/java/io/kestra/cli/commands/sys/ReindexCommand.java

It generates an exception on EE as it has dependencies not available in the CLI.

fix(cli): avoid calling the taskdefault service when reindexing flow

---

core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/runners/RetryTest.java
core/src/test/resources/flows/valids/retry-success-first-attempt.yaml

An attempt to set the `WARNING` state only when there was an actual retry attempt.
close #1929

Finish as SUCCESS when no retry attempt

---

webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/main/java/io/kestra/webserver/controllers/TaskRunController.java
webserver/src/test/java/io/kestra/webserver/controllers/TaskRunControllerTest.java

The ExecutionController is big and contains methods for the taskruns endpoint, splitting the two slightly reduce its size.
I wonder if the `/{executionId}/eval/{taskRunId}` operation may be also moved to the TaskRun endpoint, this will require to change its URL, we can deprecate the old one and add an indirection.

chore(webserver): move taskrun operations to a dedicated endpoint

---

core/src/main/java/io/kestra/core/models/flows/FlowWithException.java
jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcFlowRepository.java
ui/src/components/inputs/EditorView.vue
ui/src/stores/flow.js

Properly handle invalid flows from the UI, part of https://github.com/kestra-io/kestra/issues/1866 based on top of #1944, both PR can be review together or separately.
Some code was not compatible with FlowWithSource anymore.
@tchiotludo I keep validation on the flow editor as, even with the current code now correctly displaying an exception when loading the flow, without it when opening the editor the flow is validated (green mark) so I think it's better to validate the flow after loading it.

Fix/invalid flow from the UI

---

ui/src/components/flows/FlowRun.vue
ui/src/components/inputs/Editor.vue
ui/src/components/inputs/EditorView.vue

* Ctrl+E works in the context of Monaco Editor.
* The Ctrl+S, Ctrl+E, Enter sequence was achieved.
* Triggering the execution via `onClick()` feels hacky :(
close #1814

Add a shortcut to execute flow

---

core/src/main/java/io/kestra/core/services/FlowService.java

This occurs when the validation is triggered on a non-yet completed flow, for ex when typing or hitting save too early.

fix(core): possible NPE on validation

---

core/src/main/java/io/kestra/core/docs/DocumentationGenerator.java
core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java
webserver/src/main/java/io/kestra/webserver/controllers/PluginController.java
webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java

Previously, we change the alert block in the DocumentationGenerator so it was changed when generating the markdown used in the documentation site and for the documentation provided by th e PluginController. Moving this replacement on the PluginController only do this for the UI and not the documentation site that uses NutxJS alert block.
close #1902

fix(core, webserver): only change the alert block for the UI

---

core/src/main/java/io/kestra/core/tasks/flows/EachParallel.java
core/src/main/java/io/kestra/core/tasks/flows/EachSequential.java

to avoid situations of a flow with hundreds of tasks
For now the link to a blueprint points to the demo,; we'll replace it with the link to the blueprint on the website

Link to best practices docs and blueprint

---

core/src/main/java/io/kestra/core/runners/Worker.java

Note that this will make the task not killing but ends with the "previous" state (failed), the execution will then be marked as failed and not killed at the moment, but if #1747 is merged the execution will correctly be marked as KILLED. Anyway, currently, without this, the execution is also marked as FAILED, but the attempts continue so this PR improves the current process by short-circuiting the attempt for killed execution.

fix(core): don't retry a task if the execution is killed

---

.github/ISSUE_TEMPLATE/bug.yml

It seems that very few people are splitting the bug report into the fields `expected` vs `actual` behavior vs `flow example`. Instead, most seem to use the first field to describe the bug they see - perhaps we can use only this field + the field to explain the environment?

Simplify bug report issue template

---

core/src/main/java/io/kestra/core/models/flows/Input.java
core/src/main/java/io/kestra/core/models/flows/input/SecretInput.java
core/src/main/java/io/kestra/core/runners/RunnerUtils.java
core/src/test/java/io/kestra/core/runners/InputsTest.java
core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java
core/src/test/resources/flows/valids/inputs.yaml
ui/src/components/executions/Overview.vue
ui/src/components/flows/FlowRun.vue
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java

close [#1442](https://github.com/kestra-io/kestra/issues/1442)
When entering inputs, the input is of type password.
In the overview tab of the flow, the secret is masked.
We cannot do anything inside logs or outputs but as we don't log inputs by default, if a user logs a secret this is his responsibility (or if he copies an input into an output).

feat: new SECRET input type

---

core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/main/java/io/kestra/core/tasks/flows/Flow.java
core/src/test/java/io/kestra/core/tasks/flows/FlowCaseTest.java
core/src/test/resources/flows/valids/switch.yaml
core/src/test/resources/flows/valids/task-flow.yaml

The label inheritance is disabled by default.
Please, validate the usage of the exec repo.
close #2114

Allow a subflow to inherit calling flow's labels

---

build.gradle
core/src/test/resources/flows/valids/webhook-secret-key.yaml
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java

As the secret function adds a new line at the end of the rendered value.
close #2138

fix(webserver): trim the rendered webhook key

---

build.gradle

Reading https://stackoverflow.com/questions/27843562/how-to-configure-logback-in-spring-boot-for-ansi-color-feature Windows coloring should work by including the Jansi library.
However, this has not been tested.
close [#1958](https://github.com/kestra-io/kestra/issues/1958)

fix: add jansi lib for coloured logs support on Windows

---

ui/src/App.vue

It's useful to have the environment displayed in the title. For example, password manager auto-type or visual info in browser tabs.

Propagate the environment name to the page title

---

ui/src/components/home/HomeSummaryStatusLabel.vue

Did reduce the police size as with the breaking text is was rendering really weird and happening with not this high number.
close #1563

fix(): better dashboard responsiveness

---

webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java

When using Terraform with flow as JSON (not keeping source), the `@Valid` annotation validate the flow before we inject TaskDefaults in it, returning 422 even if the flow have taskDefaults that correctly inject required properties.
Moreover, the flow is validated a second times with the taskDefaults injected, so the @Valid one can be omit the flow will still be validated.

fix(webserver): remove flow validation before taskDefault injection

---

cli/src/main/resources/application.yml

We use it for the JDBC queue purge and the usage.
core-pool-size is the number of threads to keep in the pool, even if they are idle. Setting it to one seems enough as we schedule tasks each hour. By default, the executor uses 2*nbProc.

feat: lower the size of the Micronaut executor that handle @Scheduled

---

jdbc-postgres/src/main/resources/migrations/postgres/V1_3__postgres-queues-pkey.sql

This avoids the queues_pkey index to be used by the poll query which is suboptimal.

fix(jdbc-postgres): drop the queues_pk and use an hash index instead

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/runners/Worker.java

Also avoid double put of the worker group tag from the Worker

feat: add a tenant tag in the runcontext metrics

---

core/src/main/java/io/kestra/core/runners/VariableRenderer.java

This avoids a lot of allocation so improves performance when there is a lot of variable rendering that doesn't contain a template.
On a contrived benchmark, variable rendering cause up to 30% of allocations, with the fix down to 0 (as all variables are not templates).

feat(core): shortcircuit variable rendering when it's not a template

---

core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java
core/src/main/java/io/kestra/core/validations/ValidationFactory.java
core/src/main/java/io/kestra/core/validations/WebhookValidation.java
core/src/test/java/io/kestra/core/validations/WebhookTest.java

Validate that a Webhook trigger cannot have a condition of type MultipleCondition as this is not supported.

fet(core): add validation to the Webhook trigger

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/tasks/flows/WorkingDirectoryTest.java
core/src/test/resources/flows/valids/working-directory-taskrun.yml

The issue here is that when in a workerDirectory, we don't follow the usual paths [here](https://github.com/kestra-io/kestra/blob/4a1a8a2515dcf0931c95b2fca57407df46b28a2e/core/src/main/java/io/kestra/core/runners/ExecutorService.java#L226), the parents & parent variable isn't provided
So when we pass in[ this method](https://github.com/kestra-io/kestra/blob/4a1a8a2515dcf0931c95b2fca57407df46b28a2e/core/src/main/java/io/kestra/core/runners/RunContext.java#L403), the variable taskrun is erased.
So, in my solution, when creating children tasks inside the worker, I create a new workerTaskrun with taskRun (maybe useless, but at least the data are here), and copy parents and parent of the workerDirectory.
close #1809

fix(): add taskrun values inside workerDirectory task

---

core/src/test/java/io/kestra/core/tasks/flows/WorkingDirectoryTest.java

It is flaky, instead get the taskrun for the task ID that we want.

fix: don't blinding get task run 5 in the WorkingDirectoryTest

---

ui/src/components/inputs/Editor.vue

The _Flow - Editor_ view should feature the Monaco editor focused - it is the main focal point of the view. Having the editor focused makes the GUI-based flow editing UX smoother. There is one click less required between activating the view and typing.
---
Just try to edit any flow
---

fix(ui): Make the main Monaco editor focused by default

---

ui/src/components/flows/TriggerFlow.vue
ui/src/components/inputs/EditorView.vue
ui/src/stores/flow.js

No reference to the execution launch button is required anymore.
close #2348
---
```yaml
id: hello-world
namespace: dev
tasks:
- id: hello
message: Kestra team wishes you a great day! 👋
```
---

fix(ui): fix Ctrl-e not launching an execution

---

ui/src/components/home/Home.vue

Array.shift() return the last item and modify the array so the "last 30 days" widget didn,'t contains today and yesterday. Usingt Array.at() didn't modify the array, fixing the issue of incorrect results.
Fixes #2232

fix(ui): homepage dashboard incorrect results

---

ui/public/init.js
ui/public/vscode.html
ui/src/components/flows/TriggerFlow.vue
ui/src/components/namespace/Editor.vue
ui/src/components/namespace/NamespaceSelect.vue
ui/src/utils/submitTask.js

Link to https://github.com/kestra-io/vscode-kestra/pull/9
Those 2 PRs bring:
* Fix schema download
* Change flow folders to`_flows`
* Display execute button when on a flow file tab
* Allow creation & deletion of flows
* Use default namespace (if one is setup) when loading files editor
* warn unsaved files when leaving editor
* make editor start on a readme, create one if none exist
close #2381 
close #2367 
close #2342
close #2374

feat(ui): QOL improvement for files editor

---

.github/workflows/main.yml
Dockerfile

This added 15MB to the image as we need to install pip to do it. 
Fixes #2357

ci: add the Kestra Python library to oiur full Docker image

---

core/src/main/java/io/kestra/core/models/executions/Execution.java
core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/main/java/io/kestra/core/runners/FlowableUtils.java

Flowable tasks methods `resolveSequentialNext` and `resolveState` call multiple times `Execution.findTaskRunByTasks` which is a slow operation. This refactoring avoid some of these duplication and grealy improve perfrormance when an execution has a lot of task runs.
On contrieved benchmarks with more than 1000 task runs `ExecutorService.process` goes down from 50% of CPU time to 20%
**BEFORE**
**AFTER**

feat(core): improve performance for flowable tasks methods

---

core/src/main/java/io/kestra/core/models/executions/TaskRun.java
core/src/main/java/io/kestra/core/models/hierarchies/SubflowGraphTask.java
core/src/main/java/io/kestra/core/models/tasks/ExecutableTask.java
core/src/main/java/io/kestra/core/models/tasks/FlowableTask.java
core/src/main/java/io/kestra/core/models/tasks/RunnableTask.java
core/src/main/java/io/kestra/core/runners/ExecutableUtils.java
core/src/main/java/io/kestra/core/runners/Executor.java
core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/runners/WorkerTaskExecution.java
core/src/main/java/io/kestra/core/services/GraphService.java
core/src/main/java/io/kestra/core/tasks/flows/Flow.java
core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java
core/src/main/java/io/kestra/core/topologies/FlowTopologyService.java
core/src/main/java/io/kestra/core/utils/GraphUtils.java
core/src/main/java/io/kestra/core/validations/ValidationFactory.java
core/src/test/java/io/kestra/core/models/hierarchies/FlowGraphTest.java
core/src/test/java/io/kestra/core/tasks/flows/ForEachItemCaseTest.java
core/src/test/java/io/kestra/core/tasks/flows/ForEachItemTest.java
core/src/test/java/io/kestra/core/validations/FlowValidationTest.java
core/src/test/resources/flows/valids/for-each-item-no-wait.yaml
core/src/test/resources/flows/valids/for-each-item-subflow.yaml
core/src/test/resources/flows/valids/for-each-item.yaml
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java
runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java

Fixes https://github.com/kestra-io/kestra/issues/2131
Add a `ForEachItem` task that will split a file in batches and will trigger a subflow execution for each batch.
The current implementation will generates as many subflows as there is batches with unlimited concurrency.
---
Parent flow
```yaml
id: each-item
namespace: dev
tasks:
- id: extract
type: io.kestra.plugin.gcp.bigquery.Query
sql: |
SELECT DATETIME(datehour) as date, title, views FROM `bigquery-public-data.wikipedia.pageviews_2023` 
WHERE DATE(datehour) = current_date() and wiki = 'fr' and title not in ('Cookie_(informatique)', 'Wikipédia:Accueil_principal', 'Spécial:Recherche')
ORDER BY datehour desc, views desc
LIMIT 10000
store: true
- id: each
type: io.kestra.core.tasks.flows.ForEachItem
items: "{{ outputs.extract.uri }}" …
```

ForEachItem task

---

ui/src/components/layout/Labels.vue

The execution table can be filtered by simply clicking on an execution label. This did not work anymore - the filtering action brought seemingly random lines instead.
The same applies to the flows view filter.
---
Using a local PgSQL Kestra instance.
1. Save any flow
2. Start a new execution with label `A:B`
3. Start a new execution with label `C:D`
4. Start a new execution with label `A:B`
5. Go to Executions
6. Click on the `A:B` label
7. Only the executions featuring `A:B` are shown
---

fix(ui): fix labels filter regression

---

jdbc-h2/src/main/resources/migrations/h2/V1_9__multitenant_indices.sql
jdbc-mysql/src/main/resources/migrations/mysql/V1_10__multitenant_indices.sql
jdbc-postgres/src/main/resources/migrations/postgres/V1_10__multitenant_indices.sql

~Only add a new index for optimizing findAll(), other access should use existing indices.~
The rational is that:
- There should not be a lot of tenants in an instance (a few tens or hundreds at most)
- Existing indices will still be highly distributed as the same flow/namespace has low chance to be on multiple tenants
So the cost of updating all indexes (which means reindexing potentially large tables) with the new columns seems too high with respect to the added value.

feat(jdbc): add indices on tenant_id

---

cli/src/main/java/io/kestra/cli/commands/sys/SysCommand.java
cli/src/main/java/io/kestra/cli/commands/sys/database/DatabaseCommand.java
cli/src/main/java/io/kestra/cli/commands/sys/database/DatabaseMigrateCommand.java

Fixes #2291
To use it, the user can run Kestra in a separate container/pod or start Kestra with Flyway disabled and run the command.
To disable Flyway migration the following configuration should be used:
```properties
flyway:
datasources:
postgres:
enabled: false
mysql:
enabled: false
h2:
enabled: false
```
It needs to be documented on the migration guide, noted on each release note that have migration and our Helm chart should be improved to include a shell pod.

feat: allow running Flyway migration with a command

---

ui/src/components/executions/FilePreview.vue
ui/src/translations.json
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/main/java/io/kestra/webserver/utils/filepreview/DefaultFileRender.java
webserver/src/main/java/io/kestra/webserver/utils/filepreview/FileRenderBuilder.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
webserver/src/test/java/io/kestra/webserver/utils/filepreview/DefaultFileRenderTest.java
webserver/src/test/resources/data/iso88591.txt

* Generic files might be encoded/previewed using various code pages (such as IBM-500).
* Common encoding options were selected.

Select character encoding for file preview

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/tasks/flows/WorkingDirectoryTest.java
core/src/test/resources/flows/valids/working-directory-taskrun-nested.yml
core/src/test/resources/flows/valids/working-directory-taskrun.yml

Recap of what has been done and why : 
* Working Directory having a "custom task path," the working Directory task itself wasn't added in the `parents` and `parent` variables, preventing access to the `parent.taskrun.value` that should exist when in a flowable
* My mistake was to use a two nested flowable test for the debugging, so this time, I make a more straightforward test that uses `taskrun.value` 
* I then realized that the taskrun property of the children task was overridden in the runAttempts, and as a workingDirectory can not have flowables inside (meaning children of a `workingDirectory` could never have a `value` inside their `taskrun` property), 
* I created a new method on top of the `forWorker`  to keep logic separated, that will check if the runContext contains the …

fix(core): set taskrun value in workingDirectory children task

---

ui/src/components/namespace/Editor.vue
ui/src/components/namespace/NamespaceSelect.vue

By default our `namespaceSelect` component will display a namespace and all his level.
Example, the namespace `com.kestra.dev` will have in the select options:
* `com`
* `com.kestra`
* `com.kestra.dev`
This is great for filtering to display all flows in `com.kestra` and its children, but in the namespace files editor we only want to display the returned namespace by the endpoints, if lower level aren't returned its because there is no flows or user doesn't have access to the namespace.

feat(): only list namespace from endpoint in files editor

---

core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java

Fixes #2517
The following task:
```
- id: each
type: io.kestra.core.tasks.flows.ForEachItem
items: "somefile.txt"
batch: 
rows: 10
namespace: dev
flowId: per-item
wait: true
transmitFailed: true
inputs:
items: "{{taskrun.items}}"
```
Will generate the following log visible in the UI:

feat(core): add error logs when ForEachItem fail to create executions

---

ui/src/components/inputs/Editor.vue
ui/src/components/inputs/EditorButtons.vue
ui/src/components/inputs/EditorView.vue

Buttons were only in the editor, so if it wasn't displayed, the actions weren't too.
To fix that, I made the bottom buttons a component used at the bottom of the "editorView" if the topology is displayed.
On other views than the topology, the buttons were hiding documentation or blueprints paginations, so it will be displayed inside the editor in those case
closes #2553

fix(): display actions buttons on topology view

---

cli/src/main/java/io/kestra/cli/commands/sys/SubmitQueuedCommand.java
cli/src/main/java/io/kestra/cli/commands/sys/SysCommand.java
jdbc/src/main/java/io/kestra/jdbc/runner/AbstractJdbcExecutionQueuedStorage.java

This needs to be tested manually as the cli project uses the memory executor that didn't have concurrency support.
I use this flow to queued execution then exit Kestra, call the command, and check that executions disappear from the executionqueued table, then start Kestra and see that they are executed (queued again normally).
```
id: hello-concurrency
namespace: dev
concurrency:
limit: 1
behavior: QUEUE
tasks:
- id: hello
message: Kestra team wishes you a great day! 👋
- id: sleep
type: io.kestra.plugin.scripts.shell.Commands
runner: PROCESS
commands:
- sleep 10
```

feat(cli): SubmitQueuedCommand to submit queued executions

---

core/src/main/java/io/kestra/core/runners/ExecutorService.java
core/src/test/resources/flows/valids/sleep.yml
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java

Fixes #309 
I tried this when working on #1746, and it allows to kill the infinite loop the executor enters while without this, there is no way to kill an execution when the issue is in a flowable.
I open the PR in draft to open a discussion about it.

fix(webserver): mark the execution as killing to avoid ghost execution

---

cli/src/main/java/io/kestra/cli/commands/flows/namespaces/FlowNamespaceCommand.java
cli/src/main/java/io/kestra/cli/commands/namespaces/NamespaceCommand.java
cli/src/main/java/io/kestra/cli/commands/namespaces/files/NamespaceFilesCommand.java
cli/src/main/java/io/kestra/cli/commands/sys/database/DatabaseCommand.java
cli/src/main/java/io/kestra/cli/commands/templates/namespaces/TemplateNamespaceCommand.java
cli/src/test/java/io/kestra/cli/commands/flows/namespaces/FlowNamespaceCommandTest.java
cli/src/test/java/io/kestra/cli/commands/namespaces/NamespaceCommandTest.java
cli/src/test/java/io/kestra/cli/commands/namespaces/files/NamespaceFilesCommandTest.java
cli/src/test/java/io/kestra/cli/commands/sys/database/DatabaseCommandTest.java
cli/src/test/java/io/kestra/cli/commands/templates/namespaces/TemplateNamespaceCommandTest.java

Improved QoL of situations when interacting purely with the CLI (no documentation at hand).
Commands with missing implicit help output are hopefully gone.
---
Unit tests

fix(cli): add missing help outputs

---

jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java

Very small fix for a potential executor misbehavior

fix(jdbc): update the executor even if we cannot emit logs

---

core/src/main/java/io/kestra/core/models/executions/TaskRun.java
core/src/main/java/io/kestra/core/runners/FlowListeners.java
core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/runners/DeserializationIssuesCaseTest.java
jdbc-h2/src/test/java/io/kestra/runner/h2/H2JdbcDeserializationIssuesTest.java
jdbc-mysql/src/test/java/io/kestra/runner/mysql/MySqlJdbcDeserializationIssuesTest.java
jdbc-postgres/src/test/java/io/kestra/runner/postgres/PostgresJdbcDeserializationIssuesTest.java
jdbc/src/main/java/io/kestra/jdbc/JdbcWorkerTriggerResultQueueService.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
jdbc/src/test/java/io/kestra/jdbc/runner/AbstractJdbcDeserializationIssuesTest.java
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java

This PR provides safe deserialization for:
- A WorkerTrigger
- A WorkerTriggerResult
- A WorkerTask
- A Flow
You can QA with a flow that uses a task from a plugin, launching it thousands of times, hard killing Kestra and removing the plugin so you have pending WorkerTask and WorkerTask result to verify that it correctly ends the flow.
You can also use the following instructions to QA features one by one.
To QA an invalid `WorkerTrigger`, you can use the following INSERT statement, there should be error logs but no stacktraces or crashes.
```sql
INSERT INTO queues ("type", "key", value, updated)
VALUES('io.kestra.core.runners.WorkerJob'::"queue_type", 'company.team_hello-world_trigger', '{"type": "trigger", "trigger": {"id": "trigger", "sql": "select CURRENT_TIMESTAMP", "url": …
```

Improve deserialization error handling

---

core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java
core/src/main/java/io/kestra/core/validations/TimezoneId.java
core/src/main/java/io/kestra/core/validations/validator/TimezoneIdValidator.java
core/src/test/java/io/kestra/core/validations/TimezoneIdTest.java

Added a generic timezone ID validator to prevent misuse and typos.
close #2655
---
```yaml
id: hello-world
namespace: company.team
triggers:
- id: schedule
type: io.kestra.core.models.triggers.types.Schedule
cron: "* * * * *"
timezone: Europe/London/ # FIXME
tasks:
- id: hello
message: Kestra team wishes you a great day! 👋
```

fix(core): add missing Schedule timezone validation

---

core/src/test/java/io/kestra/core/services/TaskDefaultServiceTest.java

Adding assertions on defaults for Triggers and Conditions.
This is not documented so I wonder if we should update the documentation site here: https://kestra.io/docs/administrator-guide/configuration/others#task-defaults.

feat(core): assert that task default works for Trigger and Condition

---

core/build.gradle
core/src/main/java/io/kestra/core/models/conditions/types/DateTimeBetweenCondition.java
core/src/main/java/io/kestra/core/models/conditions/types/DayWeekCondition.java
core/src/main/java/io/kestra/core/models/conditions/types/DayWeekInMonthCondition.java
core/src/main/java/io/kestra/core/models/conditions/types/PublicHolidayCondition.java
core/src/main/java/io/kestra/core/models/conditions/types/TimeBetweenCondition.java
core/src/main/java/io/kestra/core/models/conditions/types/WeekendCondition.java
core/src/test/java/io/kestra/core/models/conditions/types/PublicHolidayConditionTest.java

Fixes #2629 
To QA it you can use the following flow and play with country and subdivision:
```yaml
id: schedule
namespace: company.team
triggers:
- id: schedule
type: io.kestra.core.models.triggers.types.Schedule
cron: "* * * * *"
conditions:
- type: io.kestra.core.models.conditions.types.PublicHolidayCondition
country: DE
date: "2023-03-08"
tasks:
- id: hello
message: Kestra team wishes you a great day! 👋
```
In this example, 2023-03-08 will not trigger a flow for country DE but will trigger a flow for country DE and subDivision BE.

feat(core): public holiday condition

---

ui/src/components/flows/MetadataEditor.vue
ui/src/components/flows/tasks/Task.js
ui/src/components/flows/tasks/TaskBasic.vue
ui/src/stores/plugins.js
ui/src/utils/yamlUtils.js

Add `concurrency` property to low code metadata form :
- When setting limit = 0, property is removed
- `TaskBasic` is similar to `TaskObject` but without the $refs needed, useful when we just want to generate a form from a definitions and not a whole json schema

feat(): added concurrency property to lowcode editor

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/runners/VariableRenderer.java
core/src/test/java/io/kestra/core/models/hierarchies/FlowGraphTest.java
core/src/test/java/io/kestra/core/runners/RunContextTest.java
core/src/test/java/io/kestra/core/runners/pebble/PebbleVariableRendererTest.java
core/src/test/resources/flows/templates/with-template.yaml
core/src/test/resources/flows/valids/return.yaml

This reverts commit 2e1c3733a4a96bb494be1aa8acad01df55b41284.
#2588 and #2585 will be re-openned after merge
Pre-rendering variables can be problematic if some variables are dynamic and costly to render (for ex using the secret function with a cloud backend).

Revert "fix(): prerender variables (#2588)"

---

.github/workflows/main.yml

close https://github.com/kestra-io/kestra/issues/2747

chore(): add concurrency property to avoid duplicate develop CI running

---

core/src/main/java/io/kestra/core/runners/NamespaceFilesService.java
core/src/test/java/io/kestra/core/runners/NamespaceFilesServiceTest.java

fix(core): NamespaceFilesService inject include / exclude patterns don't mandate a leading '/' for patterns

---

core/src/main/java/io/kestra/core/models/flows/Flow.java
core/src/main/java/io/kestra/core/runners/ExecutorService.java

Small fix of an incorrect log.
I also remove one `throwFunction` usage that was not needed.

fix(core): invalid log, should log task id and not flow id twice

---

core/src/test/java/io/kestra/core/runners/DeserializationIssuesCaseTest.java
jdbc-postgres/src/test/java/io/kestra/runner/postgres/PostgresSubflowExecutionStorageTest.java
jdbc/src/main/java/io/kestra/jdbc/runner/AbstractJdbcSubflowExecutionStorage.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
jdbc/src/test/java/io/kestra/jdbc/runner/AbstractSubflowExecutionTest.java

feat(jdbc): safely deserialize subflow executions

---

ui/src/components/settings/BasicSettings.vue

Trivial modification, the check that Template is enabled was not present so the button was displayed even if Template is disabled.

fix(ui): hide the export template button if template is not enabled.

---

core/src/main/java/io/kestra/core/runners/Worker.java
core/src/test/java/io/kestra/core/runners/RetryTest.java
core/src/test/resources/flows/valids/retry-invalid.yml

Fixes #2835 
I'm not very convinced by this, we can fix it like I did at the worker level or we can add a big try/catch on the whole method.
Another way of doing it would be to add a validation to the retry setting, for ex a validation that try to build the object and fail validation if it cannot be created. Or both the validation and this fix.

fix(core): retry can crash the Worker

---

build.gradle

This allows to install locally without signing the JARs

chore: don't sign JARs if it's not to publish them

---

cli/src/main/java/io/kestra/cli/AbstractApiCommand.java
cli/src/main/java/io/kestra/cli/AbstractCommand.java

The CLI help output regarding the default values was a bit confusing. Used just the Picocli features.
---
`./build/executable/kestra-0.14.0-SNAPSHOT -h`

fix(cli): Make the CLI help clearer

---

README.md

Fix link to RScript plugin
RScript plugin link in README linked to powershell. Changed to https://kestra.io/plugins/plugin-script-r
---
Thank you for your contribution. ❤️  -->

Docs: update README.md to fix link to RScript plugin

---

core/src/main/java/io/kestra/core/crypto/CryptoService.java
core/src/main/java/io/kestra/core/runners/pebble/Extension.java
core/src/main/java/io/kestra/core/runners/pebble/functions/DecryptFunction.java
core/src/main/java/io/kestra/core/runners/pebble/functions/EncryptFunction.java
core/src/test/java/io/kestra/core/runners/pebble/functions/EncryptDecryptFunctionTest.java

Part of #2143 but didn't fully fix the issue.
It can be QA with the following flow:
```yaml
id: cypher
namespace: company.team
tasks:
- id: encrypt
type: io.kestra.core.tasks.debugs.Return
format: "{{encrypt('toto')}}"
- id: logEncrypted
message: "{{outputs.encrypt.value}}"
- id: descrypt
type: io.kestra.core.tasks.debugs.Return
format: "{{decrypt(outputs.encrypt.value)}}"
- id: logDecrypted
message: "{{outputs.descrypt.value}}"
```
I didn't configure a key by default as it is a security risk if a user didn't change it, a message will pop up in case the user didn't specify one and the flow will be in error: `You must configure a base64 encoded AES 256 bit secret key in the 'kestra.crypto.secret-key' configuration …

feat(core): add Pebble encrypt and decrypt functions

---

.github/ISSUE_TEMPLATE/bug.yml

if you're OK with this template, I'll add it across all repos
Especially on the docs repo, this is way too many fields :)

fix: make bug report template shorter

---

ui/src/components/executions/TaskRunLine.vue
ui/src/components/logs/TaskRunDetails.vue

Task run-specific logs couldn't be downloaded - the `downloadName()` function was missing.

fix(ui): fix task run logs download

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/test/java/io/kestra/core/runners/RunContextTest.java
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java

This will allow easily encryption of output from a task (for ex for GCP OauthAccessToken).

feat: allow encryption via the RunContext

---

core/src/main/java/io/kestra/core/runners/NamespaceFilesService.java
core/src/test/java/io/kestra/core/runners/NamespaceFilesServiceTest.java

fix(core): don't crash upon injecting Namespace Files if the root folder doesn't exist

---

build.gradle
core/src/main/java/io/kestra/core/secret/SecretService.java
core/src/test/java/io/kestra/core/secret/SecretFunctionTest.java
core/src/test/resources/flows/valids/secrets.yaml

As some old base64 tool may add some.
Fixes #2249

feat(core): remove newline to allow multi-line secret

---

core/src/main/java/io/kestra/core/models/tasks/common/EncryptedString.java
core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/test/java/io/kestra/core/runners/RunContextTest.java
core/src/test/java/io/kestra/core/tasks/test/Encrypted.java
core/src/test/resources/flows/valids/encrypted-string.yaml

Will allow to automatically encrypt an output property and decrypt it at run context creation time.
Such output will be visible like that:
A use site in another task, it will be automatically decrypted, the test example uses a Return task and this task will  access the decrypted value.

feat: automatic encryption and decryption of task outputs

---

core/src/main/java/io/kestra/core/runners/ExecutorState.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java

Fixes #2976
Previously, action that must be done when an execution is terminated was done inside the method that handle messages from the execution queue. As there is a last execution message send when the execution is terminated, this lead to those methods being called two times. Moving those action after the sending of the execution solves the issue and also allow to remove a deduplication that was in place to fix the same issue on a different action.

fix(jdbc): JDBC concurrency limit

---

ui/src/components/executions/Executions.vue
ui/src/components/executions/date-select/DateFilter.vue
ui/src/components/executions/date-select/DateSelect.vue
ui/src/components/executions/date-select/RelativeDateSelect.vue
ui/src/components/layout/DateRange.vue
ui/src/components/layout/RefreshButton.vue
ui/src/translations.json
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java

As a part of the initiative towards making a "stored execution filter" (#1397) possible there is a need to deal with the current implementation of the time filter. The current implementation is not capable of filtering based on a relative date.
close #2211
---
Making the API capable of dealing with both absolute and relative time filters seems like a good idea since it adds flexibility for the clients.
The _ISO 8601 duration_ format was chosen as the representation of the relative filter as it is commonly understood.
Since the query param-based filtering was kept (it is a good thing), the absolute and relative filter pairs were made mutually exclusive.
As a part of the RFC only the `executions/search` API endpoint got modified.
---
On the UI front, the Executions view date filter was …

RFC: feature(core): relative time filter

---

ui/src/components/layout/BulkSelect.vue

The _Select all_ bulk selection button was missing inner HTML rendering which is used by the English translation.

fix(ui): render HTML inside bulk select button

---

core/src/main/java/io/kestra/core/repositories/ExecutionRepositoryInterface.java
core/src/test/java/io/kestra/core/repositories/AbstractExecutionRepositoryTest.java
jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcExecutionRepository.java
repository-memory/src/main/java/io/kestra/repository/memory/MemoryExecutionRepository.java
ui/src/components/executions/Executions.vue
ui/src/components/executions/Overview.vue
ui/src/components/executions/SetLabels.vue
ui/src/stores/executions.js
ui/src/translations.json
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java

Fixes #2633
Allow to set (add and update) execution labels for terminated executions.
Also provide bulk action for that.

feat(*): update execution labels

---

cli/src/test/java/io/kestra/cli/commands/plugins/PluginDocCommandTest.java
core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java

In case a task is not required, default to false or the documentation will display '?'.
Fixes #3145

fix(core): default documentation to required false

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/main/java/io/kestra/core/tasks/storages/Deduplicate.java
core/src/main/java/io/kestra/core/utils/MapUtils.java
core/src/test/java/io/kestra/core/tasks/storages/DeduplicateTest.java
core/src/test/java/io/kestra/core/utils/MapUtilsTest.java

This PR adds a new core task named `Deduplicate`: Deduplicate a file by retaining only the latest row for each extracted key.
Example:
```yaml
tasks:
- id: deduplicate
type: io.kestra.core.tasks.storages.Deduplicate
expr: " {{ key }}"
```
Given the following input file : 
```json
{"key": "k1", "value": "v1"}
{"key": "k2", "value": "v1"}
{"key": "k3", "value": "v1"}
{"key": "k1", "value": "v2"}
{"key": "k2", "value": "v2"}
{"key": "k2", "value": null } 
{"key": "k3", "value": "v2"}
{"key": "k1", "value": "v3"}
```
The task will give the following output file :  
```json
{"key": "k2", "value": null } 
{"key": "k3", "value": "v2"}
{"key": "k1", "value": "v3"}
```

feat(core): add new deduplicate task for storage

---

core/src/main/java/io/kestra/core/tasks/storages/FilterItems.java
core/src/test/java/io/kestra/core/tasks/storages/FilterItemsTest.java

This PR adds a new core task named Filter: Filter a file by retaining only the records that match a given expression.
Example:
```yaml
tasks:
- id: filter
type: io.kestra.core.tasks.storages.Filter
filterCondition: " {{ value % 2 == 0 }}"
filterType: INCLUDE 
errorOrNullBehavior: EXCLUDE
```
Given the following input file :
```json
{"key": "k1", "value": 1}
{"key": "k2", "value": "invalid"} // will be excluded
{"key": "k3", "value": 3}
{"key": "k4", "value": 4}
```
The task will give the following output file :
```json
{"key": "k4", "value": 4}
```

feat(core): add new Filter task for filtering records from file

---

core/src/main/java/io/kestra/core/models/tasks/FlowableTask.java
core/src/main/java/io/kestra/core/tasks/flows/Pause.java
core/src/main/java/io/kestra/core/tasks/flows/Sequential.java

Fixes #3158
In case there is no sub-tasks, the graph will generate a single node instead of a cluster of nodes.

fix(core): fix Pause task topology when no sub-tasks

---

core/src/main/java/io/kestra/core/runners/ExecutableUtils.java
core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java
core/src/test/java/io/kestra/core/runners/TaskWithAllowFailureTest.java
core/src/test/java/io/kestra/core/tasks/flows/ForEachItemCaseTest.java
core/src/test/resources/flows/valids/for-each-item-outputs.yaml
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java
runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java
ui/src/components/executions/Gantt.vue
ui/src/components/executions/TaskRunLine.vue
ui/src/components/logs/TaskRunDetails.vue

Splitting the file can take a lot of time and need access to the internal storage. That's why it should be done on the Worker.
A clever way to do this is to transform it as a Flowable task that will generates tasks to split the items, generates the execution , then merge the outputs.
Fixes https://github.com/kestra-io/kestra-ee/issues/862
ForEachItem is now a flowable task that will generate 2 subtasks: a runnable task to do the split and an executable task to generate the subflow executions. The only caveat is that those tasks needs an idea so I hardcoded the id as `$parentId-split`, `$parentId-executable` and `$parentId-merge`
It uses the output to share data between task
- The split file
- The subflowOutputBaseUri as the merge is done in another task
See the Gantt view
The outputs
And …

feat: ForEachItem as a flowable

---

core/src/test/java/io/kestra/core/runners/FlowTriggerCaseTest.java

The trigger-flow-listener-namespace-condition flow can be triggered by any of the flow of the namespace. As some flow are triggered by other, we cannot be sure that it has been triggered by the one we want to I relax the assertion.

fix(core): FlowTriggerTest

---

core/src/main/java/io/kestra/core/models/executions/LogEntry.java
core/src/test/java/io/kestra/core/runners/RunContextLoggerTest.java

Empty log lines were presented as `null` in downloaded log files. Some scripts tend to use empty log lines quite often.
```txt
2024-02-28T19:03:36.006Z INFO foo
2024-02-28T19:03:36.011Z INFO null
2024-02-28T19:03:36.016Z INFO bar
```
vs
```txt
2024-02-28T19:02:56.411Z INFO foo
2024-02-28T19:02:56.415Z INFO 
2024-02-28T19:02:56.419Z INFO bar
```
---
```yaml
id: hello-world-log
namespace: company.team
tasks:
- id: log-lines
type: io.kestra.plugin.scripts.shell.Commands
runner: PROCESS
commands:
- 'echo "foo"'
- 'echo' # empty log line
- 'echo "bar"'
```

fix(core): log empty messages

---

ui/src/mixins/dataTableActions.js

This PR attempts to fix a specific filtering bug:
* Execute more executions than the current Execution's table page size
* Skip to a page no. >1
* Add a specific unique label to an Execution on the page no. >1
* Click on the added label to filter by its value
* No executions are displayed - the page query parameter was not reset
---
Filtering by clicking on a label invokes a routing event which did not affect the paging state.

fix(ui): fix labels filter by route

---

jdbc-h2/src/main/resources/migrations/h2/V1_16__log_timestamp_index.sql
jdbc-mysql/src/main/resources/migrations/mysql/V1_16__log_timestamp_index.sql
jdbc-postgres/src/main/resources/migrations/postgres/V1_16__log_timestamp_index.sql

Fixes #2376
An issue exists in Postgres when we request ERROR logs on a wide timestamp range, it's cardinality calculation leads to ignore the existing indexes. Adding an index only on the timestamp column is a last resort for queries not finding existing indexes useful. The same index is added to the other databases even if we didn't have clues on the same issue for consistency.

feat(jdbc*): add an index on logs.timestamp

---

ui/package-lock.json
ui/package.json
ui/src/components/ErrorToast.vue
ui/src/components/flows/FlowDependencies.vue
ui/src/translations.json

Now hide the expand button once loaded and display a success message including the count of dependencies
required https://github.com/kestra-io/ui-libs/pull/29

fix(ui): make dependencies expand more clear

---

core/src/main/java/io/kestra/core/repositories/FlowRepositoryInterface.java
webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java

To reproduce it, create a flow with a task that will log, execute it and then delete it from the database (not from the UI!)
Go to the execution logs page/query the `/follow` endpoint, error is now 404. 
closes #1299

fix(controller): return 404 when flow not found in follow API

---

core/src/main/java/io/kestra/core/runners/RunContextLogger.java
core/src/main/java/io/kestra/core/secret/SecretService.java
core/src/test/java/io/kestra/core/runners/RunContextLoggerTest.java
core/src/test/java/io/kestra/core/secret/SecretFunctionTest.java

Fixes #3162
The only caveat is that we miss the nice message explaining that a secret is missing and how to add it.

feat(core): missing secret env var should return a null secret

---

core/src/main/java/io/kestra/core/runners/pebble/functions/ReadFileFunction.java
core/src/test/java/io/kestra/core/runners/pebble/functions/ReadFileFunctionTest.java

Fixes #3126
The following flow:
```yaml
id: read
namespace: myteam
description: Save and Execute the flow
tasks:
- id: Label
type: io.kestra.core.tasks.executions.Labels
labels:
toto: "{{read('toto.tata')}}"
- id: log
message: "Should fail before"
```
Will fail with:

feat(core): restrict using the read function on the Worker

---

core/src/main/java/io/kestra/core/services/StorageService.java

fix(core): Avoid creating empty files when splitting

---

core/src/main/java/io/kestra/core/queues/QueueService.java

There can be multiple subflow execution results er parent taskrun id: one for each generated subflow executions. So we must use executionId as a key instead.

feat: change the key of SubflowExecutionResult

---

core/src/main/java/io/kestra/core/runners/RunContext.java
core/src/test/java/io/kestra/core/runners/RunContextTest.java

A label with a null value will generates an exception while computing the list of variables inside the RunContext, failing to create a RunContext which can crash the executor.

fix(core): null label value can crash the executor

---

core/src/main/java/io/kestra/core/runners/pebble/AbstractIndent.java
core/src/main/java/io/kestra/core/runners/pebble/Extension.java
core/src/main/java/io/kestra/core/runners/pebble/filters/IndentFilter.java
core/src/main/java/io/kestra/core/runners/pebble/filters/NindentFilter.java
core/src/test/java/io/kestra/core/runners/pebble/filters/IndentFilterTest.java
core/src/test/java/io/kestra/core/runners/pebble/filters/NindentFilterTest.java

feat(core): add Pebble filters indent, nindent
In reference to issue #3258
With the use of YAML comes the _issue_ of indentation - especially when constructing YAML from multiple objects separately or having to nest generated YAML within an existing templated structure. Thus I created filters that would enable to add indentation.
Both filters support original line breaks that were used in the input string, nindent adds the same type of newline, thus it should be safe to use with for example, jq configuration, shell scripts, etc. Support is for CRLF, LFCR, CR, LF.
Use `indent` to _indent_ all lines except for the first one.
Amount is required and defines how many times prefix is repeated before each line (except for the first one).
Prefix defines what is used to indent the lines. By …

feat(core): add Pebble filters indent, nindent

---

core/src/main/java/io/kestra/core/runners/pebble/Extension.java
core/src/main/java/io/kestra/core/runners/pebble/filters/YamlFilter.java
core/src/main/java/io/kestra/core/runners/pebble/functions/YamlFunction.java
core/src/test/java/io/kestra/core/runners/pebble/filters/YamlFilterTest.java
core/src/test/java/io/kestra/core/runners/pebble/functions/YamlFunctionTest.java
ui/src/components/logs/LogsWrapper.vue

In reference to issue #3258
Similarily to `json()` [function](https://kestra.io/docs/concepts/expression/function#json) [[code](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/functions/JsonFunction.java)] support the deserialization / objectification of YAML strings to variables.
Similarily to `| json` [filter](https://kestra.io/docs/concepts/expression/filter/json#json) [[code](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/filters/JsonFilter.java)] support the serialization / construction of YAML strings from variables.
Tests for both YamlFilter and YamlFunction are included in the PR.
Sample code for testing YAML filter and function in Kestra tasks.
```yaml
id: …
```

feat(core): add Pebble YAML filter and YAML function

---

ui/src/components/executions/Executions.vue
ui/src/components/flows/Flows.vue
ui/src/components/logs/LogsWrapper.vue
ui/src/components/saved-filters/Filters.vue
ui/src/components/saved-filters/SavedFilter.vue
ui/src/stores/filters.js
ui/src/stores/store.js
ui/src/translations.json
ui/src/utils/constants.js

This PR brings a minimal working version of user-specific saved execution filters. Now it's possible to improve UX by recalling frequently used queries by a single click. 
* This implementation targets the `localStorage` - no advanced features like sharing or persisting the saved filters are present.
* Styling/UX/naming needs to be reviewed & corrected to fit Kestra visuals.
* French translation is missing 🙃
close #1397
---

feat(ui): add minimal version of saved search filters

---

build.gradle
core/src/main/resources/logback/base.xml
core/src/main/resources/logback/ecs.xml
core/src/main/resources/logback/gcp.xml
core/src/main/resources/logback/text.xml

Fixes #3172
Thanks to this new log configuration, there is now logs for Flyway which would avoid thinking that nothing happens when a long migration is in process:
```
2024-03-12 10:52:47,520 INFO  main         o.f.core.internal.command.DbMigrate Current version of schema "public": 1.20
2024-03-12 10:52:47,523 INFO  main         o.f.core.internal.command.DbMigrate Schema "public" is up to date. No migration necessary.
```

feat(core): enable Flyway migration logs

---

cli/src/main/java/io/kestra/cli/AbstractValidateCommand.java
cli/src/main/java/io/kestra/cli/commands/flows/FlowValidateCommand.java
cli/src/main/java/io/kestra/cli/commands/templates/TemplateValidateCommand.java
cli/src/test/java/io/kestra/cli/commands/flows/FlowValidateCommandTest.java
cli/src/test/resources/warning/flow-with-warning.yaml

Fixes #3124
When a flow has warning, they are now displayed in the console when calling the `flow validate` command.
See for ex:
```
✓ - system / warning
⚠ - tasks[0] is deprecated
⚠ - The system namespace is reserved for background workflows intended to perform routine tasks such as sending alerts and purging logs. Please use another namespace name.
```

feat(cli): add warnings to the flow validate command

---

ui/src/components/saved-filters/Filters.vue
ui/src/translations/en.json

In this case disabled dropdown item represents a _selected_ filter. Using the primary color.
close #3319
---

fix(ui): improve selected filter highlight

---

core/src/main/java/io/kestra/core/repositories/LocalFlowRepositoryLoader.java

Having validation errors set to the debug log level make it hard to troubleshoot situations like:
* `kestra server local -f=<flow_dir>`
* plugin-template's [`RunnerTest`](https://github.com/kestra-io/plugin-template/blob/9747a06afd1ab3d04294d9ce73fa9af05933f825/src/test/java/io/kestra/plugin/templates/ExampleRunnerTest.java#L41)
---
PS: apparently, the log level used to be set to warning.

fix(core): warn on failed local flow parsing

---

core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java
core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java
core/src/main/java/io/kestra/core/models/annotations/Plugin.java
core/src/main/java/io/kestra/core/models/annotations/PluginProperty.java
core/src/main/java/io/kestra/core/models/script/ScriptRunner.java
core/src/main/java/io/kestra/core/models/script/types/ProcessScriptRunner.java
core/src/main/resources/docs/macro.peb
core/src/main/resources/docs/task.peb
core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java
core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java
ui/src/components/layout/Markdown.vue
ui/src/utils/markdown.js

Fixes #3344
A beta plugin must be annotated with `@Plugin(beta=true)`.
It will be displayed as following:
Note, the same apply for beta properties which must be annotated with `@PluginProperty(beta=true)`.

feat(core,ui): allow marking plugin and propertes as beta

---

core/src/test/java/io/kestra/core/models/script/AbstractScriptRunnerTest.java

Otherwhise, script runner that handle resuming job will fail tests

fix(core): use a different taskrun for each script runner test

---

cli/src/main/resources/application.yml
core/src/main/java/io/kestra/core/repositories/ServiceInstanceRepositoryInterface.java
core/src/main/java/io/kestra/core/server/AbstractServiceLivenessCoordinator.java
core/src/main/java/io/kestra/core/server/AbstractServiceLivenessTask.java
core/src/main/java/io/kestra/core/server/ServerConfig.java
core/src/main/java/io/kestra/core/server/Service.java
core/src/main/java/io/kestra/core/server/WorkerConfig.java
core/src/main/java/io/kestra/core/server/WorkerTaskRestartStrategy.java
core/src/test/java/io/kestra/core/server/ServiceInstanceTest.java
core/src/test/java/io/kestra/core/server/ServiceLivenessManagerTest.java
jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcServiceInstanceRepository.java
jdbc/src/main/java/io/kestra/jdbc/runner/JdbcServiceLivenessCoordinator.java
jdbc/src/test/java/io/kestra/jdbc/repository/AbstractJdbcServiceInstanceRepositoryTest.java
jdbc/src/test/java/io/kestra/jdbc/server/JdbcServiceLivenessManagerTest.java
repository-memory/src/main/java/io/kestra/repository/memory/MemoryServiceInstanceRepository.java

Changes:
- add new config 'kestra.server.taskRestartStrategyOnWorkerFailure'
- update default value for 'kestra.server.liveness.initialDelay' to match timeout
- fix schedule initial delay to 0
- cleanup javadoc
Fix: #3343
Fix: #3351

feat(core): add task restart strategy on worker failure (#3343,#3351)

---

ui/src/components/executions/date-select/DateFilter.vue

A rather crude way to apply the default relative filter value was added.
close #3289

fix(ui): remove absolute filter on switch away to the relative one

---

core/src/main/java/io/kestra/core/serializers/FileSerde.java
core/src/main/java/io/kestra/core/serializers/JacksonMapper.java
core/src/main/java/io/kestra/core/serializers/ion/IonFactory.java
core/src/test/java/io/kestra/core/serializers/FileSerdeTest.java

Hi Kestra!
This pull-request introduces several enhancements to I/O operations on ION files, aimed at improving performance, optimizing memory usage and providing better management of large datasets.
- Following [Jackson library best practices](https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#basics-things-you-should-do-anyway), the new code uses `MappingIterator` and `SequenceWriter`, combined with an `IonSystem` configured to support line-by-line writing.
- The instances of `MappingIterator` and `SequenceWriter` maintain their own context, resulting in faster processing, as their internal objects are reused for each line. Also, these instances also improve memory usage as they read/write data directly from/to the stream, avoiding the need for an …

refactor(core): add reactive methods in FileSerde to optimize read/write performance of ION files

---

ui/src/mixins/dataTableActions.js
ui/src/utils/eventsRouter.js

Redundant API requests waste backend resources.
* Applying a data table (e.g. Executions or Flows) filter, such as a specific namespace, resulted in two identical search requests. Since the `page` query param is present even when its value equals `1` this proposed fix is valid.
* Navigation often emitted multiple identical stats events. Identical events most probably skewed the stats.

fix(ui): prevent superfluous API requests

---

core/src/main/java/io/kestra/core/runners/Worker.java

This should be safe to purge the map at this stage.
And should fix a small memory leak when killing task often.

fix(core): remove the killed execution from the map after killing it

---

core/src/main/java/io/kestra/core/runners/Executor.java

This commit adds an optional seqId property to the Execution model object that can be used to detect concurrent updates.

chore: add optional sequential id to execution
