kestra-io/kestra

.gitignore, core/src/main/java/org/kestra/core/exceptions/IllegalVariableEvaluationException.java, core/src/main/java/org/kestra/core/models/executions/Execution.java, core/src/main/java/org/kestra/core/models/flows/Flow.java, core/src/main/java/org/kestra/core/models/hierarchies/FlowTree.java, core/src/main/java/org/kestra/core/models/tasks/FlowableTask.java, core/src/main/java/org/kestra/core/models/tasks/Task.java, core/src/main/java/org/kestra/core/runners/AbstractExecutor.java, core/src/main/java/org/kestra/core/runners/RunContext.java, core/src/main/java/org/kestra/core/runners/RunContextLogger.java, core/src/main/java/org/kestra/core/runners/VariableRenderer.java, core/src/main/java/org/kestra/core/runners/Worker.java, core/src/main/java/org/kestra/core/services/ExecutionService.java, core/src/main/java/org/kestra/core/services/TreeService.java, core/src/main/java/org/kestra/core/tasks/flows/EachSequential.java, core/src/main/java/org/kestra/core/tasks/flows/Parallel.java, core/src/main/java/org/kestra/core/tasks/flows/Sequential.java, core/src/main/java/org/kestra/core/tasks/flows/Switch.java, core/src/main/java/org/kestra/core/utils/Either.java, core/src/main/java/org/kestra/core/utils/Rethrow.java, core/src/test/java/org/kestra/core/Helpers.java, core/src/test/java/org/kestra/core/models/hierarchies/FlowTreeTest.java, core/src/test/java/org/kestra/core/tasks/flows/VariablesTest.java, core/src/test/resources/flows/valids/variables-invalid.yaml, docker-compose-dev.yml, runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutor.java, runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java, runner-memory/src/main/java/org/kestra/runner/memory/MemoryExecutor.java, webserver/src/main/java/org/kestra/webserver/controllers/ExecutionController.java, webserver/src/main/java/org/kestra/webserver/controllers/FlowController.java
mostly when invalid variable, the executor will raise an exception, the executor will crash and the flow was keep running.
Now we catch the exception and pass the execution to failed
=> fix(core): handle case executor will failed but invalid flow

ui/src/components/executions/ExecutionOutput.vue, ui/src/components/graph/TreeNode.vue
=> fix(ui): manage output with values from output panel and generate links accodingly in topology

cli/src/main/java/org/kestra/cli/App.java, cli/src/main/java/org/kestra/cli/commands/plugins/PluginDocCommand.java, cli/src/main/java/org/kestra/cli/commands/plugins/PluginInstallCommand.java, cli/src/main/java/org/kestra/cli/commands/plugins/PluginListCommand.java, cli/src/main/java/org/kestra/cli/commands/servers/StandAloneCommand.java
Hello
I've added some exception, and fix description.
Please check.
Thanks.
=> Fix description in command-plugin

core/src/main/java/org/kestra/core/services/FlowService.java
=> fix(flow): add correct pagination total value to flow aggregation route

ui/src/components/executions/Executions.vue
=> feat(ui): better display for running and created tasks states. no information in end date and duration properly recomputed from now.

ui/src/components/executions/Gantt.vue
lint is done in #136 merge it before to have a small diff here.
=> feat(ui): display value on gantt when available

core/src/main/java/org/kestra/core/models/tasks/Task.java, core/src/main/java/org/kestra/core/tasks/flows/EachSequential.java, core/src/main/java/org/kestra/core/tasks/flows/Sequential.java, core/src/main/java/org/kestra/core/tasks/flows/Switch.java, core/src/test/resources/flows/valids/all-flowable.yaml
=> fix(core): remove error on Task and keep it only on FlowableTask

ui/src/components/flows/Flows.vue, ui/src/components/flows/TriggerAvatar.vue, ui/src/components/flows/TriggerDetailsModal.vue
* no more errors in console
* conditional display handled properly
* ux consistancy : modal exists when show event is fired, so it is displayed immediately (on first click)
* try avoid somehow duck typing for trigger data model
=> fix(ui): trigger modals consistant lifecycle

core/src/main/java/org/kestra/core/models/triggers/Trigger.java, core/src/main/java/org/kestra/core/queues/QueueInterface.java, core/src/main/java/org/kestra/core/services/FlowService.java, core/src/main/java/org/kestra/core/utils/ListUtils.java, core/src/test/java/org/kestra/core/repositories/AbstractFlowRepositoryTest.java, indexer-kafka-elasticsearch/src/main/java/org/kestra/indexer/KafkaElasticIndexer.java, indexer-kafka-elasticsearch/src/test/java/org/kestra/indexer/KafkaElasticIndexerTest.java, repository-elasticsearch/src/main/java/org/kestra/repository/elasticsearch/ElasticSearchFlowRepository.java, repository-memory/src/main/java/org/kestra/repository/memory/MemoryFlowRepository.java, runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaQueue.java, runner-memory/src/main/java/org/kestra/runner/memory/MemoryQueue.java
=> fix(core): Remove trigger last execution when we remove the trigger

runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaExecutor.java, runner-kafka/src/main/java/org/kestra/runner/kafka/streams/DeduplicationTransformer.java, runner-kafka/src/main/java/org/kestra/runner/kafka/streams/ExecutionNextsDeduplicationTransformer.java, runner-memory/src/main/java/org/kestra/runner/memory/MemoryExecutor.java
=> fix(core): prevent FlowableTask to hit Workers

core/src/main/java/org/kestra/core/exceptions/IllegalVariableEvaluationException.java, core/src/main/java/org/kestra/core/runners/AbstractExecutor.java, core/src/main/java/org/kestra/core/runners/FlowableUtils.java, core/src/test/java/org/kestra/core/Helpers.java, core/src/test/java/org/kestra/core/tasks/flows/EachSequentialTest.java, core/src/test/resources/flows/valids/each-null.yaml, runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java, runner-kafka/src/test/resources/application.yml, runner-memory/src/main/java/org/kestra/runner/memory/MemoryExecutor.java
=> fix(core): handle null value on Each

ui/src/components/executions/Gantt.vue
not really sure it does what you want @tchiotludo , but it should do what you explained me :)
=> feat(ui): sort gant

ui/src/components/executions/Gantt.vue
* when there is many tasks in an execution, repaint delay is longer so the client computes less
* realtime and fix time repaint durations in header
=> Optimize gantt

core/src/main/java/org/kestra/core/runners/FlowableUtils.java, core/src/main/java/org/kestra/core/runners/handlebars/helpers/JsonHelper.java, core/src/main/java/org/kestra/core/tasks/flows/EachParallel.java, core/src/main/java/org/kestra/core/tasks/flows/EachSequential.java, core/src/test/java/org/kestra/core/Helpers.java, core/src/test/java/org/kestra/core/tasks/flows/EachSequentialTest.java, core/src/test/resources/flows/valids/each-null.yaml, core/src/test/resources/flows/valids/each-object.yaml
=> feat(tasks): handle each value with complex object

ui/src/components/executions/Executions.vue, ui/src/components/taskruns/TaskRuns.vue
=> fix(ui): inverted date in execution and taskruns

core/src/main/java/org/kestra/core/models/conditions/types/MultipleCondition.java, core/src/main/java/org/kestra/core/services/FlowService.java, core/src/test/java/org/kestra/core/runners/RestartCaseTest.java, runner-kafka/src/main/java/org/kestra/runner/kafka/KafkaQueue.java, runner-kafka/src/test/java/org/kestra/runner/kafka/KafkaRunnerTest.java
=> fix(kafka-runner): fix kafka subscribe that can be late and force a consuming with a timestamp

core/src/main/java/org/kestra/core/tasks/scripts/Bash.java
Hello !
Following up our slack conversation, here is my fabulous PR
=> fix(docs): Bash docs typo

core/src/main/java/org/kestra/core/models/flows/Input.java, core/src/test/java/org/kestra/core/runners/InputsTest.java, ui/src/components/flows/ExecutionConfiguration.vue
=> feat(input): add input description support

cli/src/main/java/io/kestra/cli/commands/sys/RestoreQueueCommand.java, cli/src/main/java/io/kestra/cli/services/RestoreQueueService.java, core/src/main/java/io/kestra/core/runners/AbstractExecutor.java, core/src/main/java/io/kestra/core/services/TaskDefaultService.java, core/src/test/java/io/kestra/core/runners/RunContextTest.java, core/src/test/java/io/kestra/core/runners/TaskDefaultsCaseTest.java, core/src/test/java/io/kestra/core/services/TaskDefaultServiceTest.java, core/src/test/resources/flows/tests/task-defaults.yaml, runner-kafka/src/main/java/io/kestra/runner/kafka/KafkaExecutor.java, runner-kafka/src/main/java/io/kestra/runner/kafka/services/KafkaStreamSourceService.java, runner-kafka/src/test/java/io/kestra/runner/kafka/KafkaExecutorTest.java, runner-kafka/src/test/java/io/kestra/runner/kafka/KafkaRunnerTest.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java
=> fix(core): handle taskDefaults also on Flowable task

core/src/main/java/io/kestra/core/models/executions/statistics/ExecutionCount.java, core/src/main/java/io/kestra/core/models/executions/statistics/Flow.java, core/src/main/java/io/kestra/core/repositories/ExecutionRepositoryInterface.java, core/src/main/java/io/kestra/core/tasks/executions/Counts.java, repository-elasticsearch/build.gradle, repository-elasticsearch/src/main/java/io/kestra/repository/elasticsearch/ElasticSearchExecutionRepository.java, repository-elasticsearch/src/test/java/io/kestra/core/tasks/executions/CountsTest.java, repository-elasticsearch/src/test/java/io/kestra/repository/elasticsearch/ElasticSearchExecutionRepositoryTest.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryExecutionRepository.java, ui/src/components/executions/Executions.vue, ui/src/components/executions/Overview.vue, ui/src/components/flows/Flows.vue, ui/src/components/layout/DateRange.vue, ui/src/components/taskruns/TaskRuns.vue, ui/src/utils/queryBuilder.js, webserver/src/main/java/io/kestra/webserver/controllers/StatsController.java
also refactor the whole ui to use zoned date time
close #339
=> feat(tasks): add an execution counts task

core/src/main/java/io/kestra/core/models/tasks/RunnableTask.java, core/src/main/java/io/kestra/core/models/tasks/Task.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/tasks/scripts/AbstractBash.java, core/src/main/java/io/kestra/core/tasks/scripts/AbstractPython.java, core/src/main/java/io/kestra/core/tasks/scripts/BashService.java
=> refactor(task): refactor bash task and introduce a global tempDir / cleanup

core/src/main/java/io/kestra/core/tasks/flows/Template.java, core/src/main/java/io/kestra/core/tasks/scripts/AbstractPython.java, runner-kafka/src/main/java/io/kestra/runner/kafka/streams/FlowJoinerTransformer.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java
=> fix(core): template must not be send on webserver

core/src/main/java/io/kestra/core/models/tasks/Output.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/runners/WorkerTask.java, core/src/main/java/io/kestra/core/tasks/scripts/AbstractBash.java, core/src/main/java/io/kestra/core/tasks/scripts/ScriptOutput.java, core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java, core/src/test/java/io/kestra/core/tasks/BashTest.java, core/src/test/resources/flows/valids/bash-warning.yaml, webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java
=> feat(core): change state to WARNING if any error on stdErr for all Bash task

.github/CONTRIBUTING.md
=> fix: typo in contributing.md

core/src/main/java/io/kestra/core/models/flows/State.java, core/src/main/java/io/kestra/core/runners/ExecutionDelay.java, core/src/main/java/io/kestra/core/runners/Executor.java, core/src/main/java/io/kestra/core/runners/ExecutorService.java, core/src/main/java/io/kestra/core/tasks/flows/Pause.java, core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/tasks/flows/PauseTest.java, core/src/test/resources/flows/valids/pause-delay.yaml, runner-kafka/src/main/java/io/kestra/runner/kafka/executors/ExecutorMain.java, runner-kafka/src/main/java/io/kestra/runner/kafka/streams/ExecutorPausedTransformer.java, runner-kafka/src/test/java/io/kestra/runner/kafka/KafkaExecutorTest.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java
=> feat(core): add a delay on Pause task in order to restart automatically after some delay

.gitpod.yml, docker-compose-ci.yml, docker-compose.yml
Replace `wait-for-it` healtcheck to start kestra by docker healthchecks
Bonus: add initial gitpod support.
=> Feat add healthcheck

ui/src/App.vue
=> feat(ui): fix theme resources joined with extra /

core/src/main/java/io/kestra/core/repositories/ExecutionRepositoryInterface.java, core/src/main/java/io/kestra/core/repositories/LogRepositoryInterface.java, core/src/main/java/io/kestra/core/services/ExecutionService.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java, core/src/main/java/io/kestra/core/tasks/storages/Purge.java, core/src/test/java/io/kestra/core/repositories/AbstractExecutionRepositoryTest.java, core/src/test/java/io/kestra/core/repositories/AbstractExecutionServiceTest.java, core/src/test/java/io/kestra/core/repositories/AbstractLogRepositoryTest.java, jdbc-h2/src/test/java/io/kestra/repository/h2/H2ExecutionServiceTest.java, jdbc-mysql/src/test/java/io/kestra/repository/mysql/MysqlExecutionServiceTest.java, jdbc-postgres/src/test/java/io/kestra/repository/postgres/PostgresExecutionServiceTest.java, jdbc/src/main/java/io/kestra/jdbc/AbstractJdbcRepository.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcExecutionRepository.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcLogRepository.java, repository-elasticsearch/build.gradle, repository-elasticsearch/src/main/java/io/kestra/repository/elasticsearch/AbstractElasticSearchRepository.java, repository-elasticsearch/src/main/java/io/kestra/repository/elasticsearch/ElasticSearchExecutionRepository.java, repository-elasticsearch/src/main/java/io/kestra/repository/elasticsearch/ElasticSearchLogRepository.java, repository-elasticsearch/src/test/java/io/kestra/repository/elasticsearch/ElasticSearchExecutionServiceTest.java, repository-elasticsearch/src/test/resources/application.yml, repository-memory/src/main/java/io/kestra/repository/memory/MemoryExecutionRepository.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryLogRepository.java
=> feat(core): add a purge task

webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> wait for an execution

core/src/main/java/io/kestra/core/tasks/scripts/runners/DockerScriptRunner.java
refactored docker image pull log debug message
fixes #768
=> KESTRA-768 - fix debug log

.github/CONTRIBUTING.md, .gitignore
This PR includes:
* css fixes 
* adds a tooltip on Executions > Outputs > task select because task Ids can be long
* updated contribution documentation to include local dev and CORS configuration
* updated gitignore to exclude .class files
fixes #775
=> KESTRA-775 - fix eval button

.github/CONTRIBUTING.md, README.md
Small typos and improvements on the README and the CONTRIBUTING guide.
=> doc: readme and contributing improvements

build.gradle
So test will pass on any system with any locale.
=> test: setup language and country system props

.github/CONTRIBUTING.md
I modified some steps of the frontend configuration to be up to date following the migration to Vite.
close #894
=> Update frontend configuration steps in CONTRIBUTING.md

core/src/main/java/io/kestra/core/tasks/scripts/Bash.java
Additional examples should help using Outputs & Metrics.
=> Document Bash plugin Outputs & Metrics

ui/package-lock.json, ui/package.json, ui/src/charts/MatrixChart.js, ui/src/charts/TreeMapChart.js, ui/src/components/flows/FlowRoot.vue, ui/src/components/flows/Overview.vue, ui/src/components/home/Home.vue, ui/src/components/home/HomeDescription.vue, ui/src/components/home/HomeSummaryFailed.vue, ui/src/components/home/HomeSummaryLog.vue, ui/src/components/home/HomeSummaryNamespace.vue, ui/src/components/home/HomeSummaryPie.vue, ui/src/components/home/HomeSummaryStatusLabel.vue, ui/src/components/home/NamespaceTreeMap.vue, ui/src/components/home/StatusPie.vue, ui/src/components/layout/DateRange.vue, ui/src/main.js, ui/src/override/components/LeftMenu.vue, ui/src/routes/routes.js, ui/src/translations.json, ui/src/utils/init.js
Migrate dashboard from Home & flow Overview from EE to OS
=> Feature migration

core/src/main/java/io/kestra/core/models/tasks/common/FetchOutput.java, core/src/main/java/io/kestra/core/models/tasks/common/FetchType.java
I choose to put them in a common subpackage as we may add more common classes later.
=> feat: add common task classes

core/src/main/java/io/kestra/core/tasks/scripts/runners/DockerScriptRunner.java
- Use a random name for the Docker container
- cleanup
=> fix docker container name

ui/src/components/graph/TreeNode.vue, ui/src/components/logs/LogList.vue, ui/src/components/plugins/Plugin.vue, ui/src/components/plugins/TaskIcon.vue
=> Feat(UI/Execution): Added task logo in Logs tab

core/src/main/java/io/kestra/core/runners/ExecutionDelay.java, core/src/main/java/io/kestra/core/runners/ExecutorService.java, core/src/main/java/io/kestra/core/tasks/flows/Pause.java, core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/tasks/flows/PauseTest.java, core/src/test/resources/flows/valids/pause-timeout.yaml, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java, webserver/src/test/java/io/kestra/webserver/controllers/FlowControllerTest.java
=> feat(core): handle timeout on Pause task

build.gradle, core/src/main/java/io/kestra/core/repositories/TriggerRepositoryInterface.java, core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcTriggerRepository.java, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcScheduler.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryTriggerRepository.java
Fixes #835
Well, should fix as the issue is not easly reproducible but this should avoid the race condition of deleting it from the Kafka Stream.
=> feat: remove trigger on flow update from the scheduler

core/src/main/java/io/kestra/core/docs/ClassPluginDocumentation.java, core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java, core/src/main/java/io/kestra/core/models/annotations/Metric.java, core/src/main/java/io/kestra/core/models/annotations/Metrics.java, core/src/main/java/io/kestra/core/models/annotations/Plugin.java, core/src/main/java/io/kestra/core/models/executions/metrics/Counter.java, core/src/main/java/io/kestra/core/models/executions/metrics/Timer.java, core/src/main/java/io/kestra/core/tasks/debugs/Return.java, core/src/main/resources/docs/task.hbs, core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java, core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java
Prototype of annotation for plugin metric documentation
=> feat(core): document metrics

core/src/main/java/io/kestra/core/tasks/executions/Fail.java, core/src/main/resources/icons/io.kestra.core.tasks.executions.Fail.svg, core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/tasks/executions/FailTest.java, core/src/test/resources/flows/valids/fail-on-condition.yaml, core/src/test/resources/flows/valids/fail-on-switch.yaml
=> feat(core): add a Fail task

.gitattributes
Fixed script EOL setting makes working with the Windows/WSL platform easier.
=> Add basic .gitattributes

core/src/main/java/io/kestra/core/tasks/scripts/runners/ProcessBuilderScriptRunner.java
Used JDK9+ tooling to create a snapshot of the whole process tree.
close #1132
=> Attempt to kill the whole process tree

ui/src/components/inputs/Editor.vue, ui/src/override/components/LeftMenu.vue, ui/src/styles/layout/element-plus-overload.scss, ui/src/styles/layout/vue-tour-overload.scss
=> feat(): new UI improvements

core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> fix(webserver): fix Key of null value missing in the webhook

core/src/main/java/io/kestra/core/models/flows/Flow.java, core/src/main/java/io/kestra/core/models/triggers/types/Flow.java, core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java, core/src/main/java/io/kestra/core/runners/RunnerUtils.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java, core/src/main/java/io/kestra/core/tasks/states/Set.java
Will fix the current documentation issues like
=> Fix task doc

ui/src/components/executions/MetricsTable.vue
=> feat(ui): change metrics column order to put 'tasg' last

ui/src/components/graph/Topology.vue
=> Flow validation is now triggered on every view

ui/src/stores/plugins.js, webserver/src/main/java/io/kestra/webserver/controllers/PluginController.java
This align the documentation from the UI with the one from the website
Fixes #1182
=> fix: don't display task base properties by default

core/src/main/java/io/kestra/core/tasks/storages/PurgeExecution.java
A minor fix for the generated Markdown.
=> Fix broken PurgeExecution doc format

ui/src/components/onboarding/OnboardingBottom.vue
=> Update Onboarding guide to include the new video 

ui/src/stores/flow.js, webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java
=> fix(): loadFlow with revision

ui/src/components/flows/tasks/TaskComplex.vue
=> fix(): use of "this" in template

ui/src/components/inputs/Editor.vue
=> fix(): Correct apply in editor

ui/src/components/executions/Gantt.vue
=> Gantt durations are now properly displayed

ui/src/components/flows/ValidationError.vue
=> fix(core): Better contrast in validation error tooltip

ui/src/components/flows/FlowCreate.vue
=> fix(): Added route info in flow creation

core/src/main/java/io/kestra/core/docs/ClassDocumentation.java, core/src/main/java/io/kestra/core/docs/ClassInputDocumentation.java, core/src/main/java/io/kestra/core/docs/DocumentationGenerator.java, core/src/main/java/io/kestra/core/models/flows/input/DateInput.java, core/src/main/java/io/kestra/core/models/flows/input/DateTimeInput.java, core/src/main/java/io/kestra/core/models/flows/input/DurationInput.java, core/src/main/java/io/kestra/core/models/flows/input/FileInput.java, core/src/main/java/io/kestra/core/models/flows/input/FloatInput.java, core/src/main/java/io/kestra/core/models/flows/input/IntInput.java, core/src/main/java/io/kestra/core/models/flows/input/TimeInput.java, core/src/test/java/io/kestra/core/runners/InputsTest.java, core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java, core/src/test/resources/flows/valids/inputs.yaml, ui/src/components/flows/MetadataInputs.vue, ui/src/components/flows/tasks/TaskBoolean.vue, ui/src/stores/plugins.js, webserver/src/main/java/io/kestra/webserver/controllers/PluginController.java
=> feat(core): validate DATE, DATETIME, DURATION, FILE, FLOAT & TIME inputs

core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/repositories/AbstractFlowRepositoryTest.java, core/src/test/resources/flows/valids/minimal2.yaml, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcExecutionRepository.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcFlowRepository.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcLogRepository.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcTemplateRepository.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryFlowRepository.java, webserver/src/test/java/io/kestra/webserver/controllers/FlowControllerTest.java
=> fix(jdbc): properly select on namespace and sub-namespace

core/src/main/java/io/kestra/core/serializers/YamlFlowParser.java, core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java, core/src/test/resources/flows/invalids/invalid-property.yaml
close [#1154](https://github.com/kestra-io/kestra/issues/1154)
=> fix: improve error message for invalid task property

ui/src/components/graph/Topology.vue
=> Topology view as portrait by default

core/src/main/java/io/kestra/core/runners/VariableRenderer.java, core/src/test/java/io/kestra/core/runners/pebble/PebbleVariableRendererTest.java
close https://github.com/kestra-io/kestra/issues/1244
=> fix(core): allow usage of Pebble raw tag in our recursive renderer

ui/src/utils/yamlUtils.js
=> fix(ui): Doc now display correctly even with cursor at end of task.

core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java
=> fix(core): use a storage prefix with executionId for triggers

ui/src/components/flows/FlowMetrics.vue, ui/src/components/home/NamespaceTreeMap.vue, ui/src/components/home/StatusPie.vue, ui/src/components/stats/StateChart.vue
=> fix(ui): Tooltip now correctly disappear on charts

ui/src/components/executions/ExecutionOutput.vue
=> fix(ui): Fix clear filter in execution outputs

ui/package.json
=> Fix(ui): Lower vue-flow version

ui/src/components/templates/TemplateEdit.vue
=> fix(ui): Templatee CTRL-S is not working

ui/src/components/settings/Settings.vue
=> fix(ui): JS error when exporting flows or templates from the settings

ui/src/components/inputs/Editor.vue
=> fix(ui): Fix editor theme when theme is light and editor is dark

ui/src/components/graph/Topology.vue
=> fix(ui): Limit size reduction of windows in editor

ui/src/stores/flow.js
=> fix(ui): No progress bar when using editor

core/src/main/java/io/kestra/core/runners/ExecutorService.java, core/src/test/java/io/kestra/core/Helpers.java, core/src/test/java/io/kestra/core/tasks/flows/BadFlowableTest.java, core/src/test/java/io/kestra/core/tasks/test/BadSequential.java, core/src/test/resources/flows/valids/flowable-fail.yaml
close https://github.com/kestra-io/kestra-ee/issues/212
=> fix(core): flowable task can fail on resolveState

core/src/main/java/io/kestra/core/validations/ValidationFactory.java, core/src/test/java/io/kestra/core/models/flows/FlowTest.java, core/src/test/resources/flows/invalids/duplicate-inputs.yaml
=> fix(core): input with duplicate name should throw a violation

ui/src/components/executions/ExecutionOutput.vue, ui/src/components/layout/Pagination.vue
=> feat(ui): Paginate outputs

core/src/main/java/io/kestra/core/queues/QueueInterface.java, core/src/main/java/io/kestra/core/queues/WorkerTaskQueueInterface.java, core/src/main/java/io/kestra/core/runners/Worker.java, jdbc-h2/src/main/java/io/kestra/runner/h2/H2Queue.java, jdbc-h2/src/main/java/io/kestra/runner/h2/H2WorkerTaskQueue.java, jdbc-h2/src/main/resources/migrations/h2/V13__queues_consumer_group.sql, jdbc-mysql/src/main/java/io/kestra/runner/mysql/MysqlQueue.java, jdbc-mysql/src/main/java/io/kestra/runner/mysql/MysqlWorkerTaskQueue.java, jdbc-mysql/src/main/resources/migrations/mysql/V11__queues_consumer_group.sql, jdbc-postgres/src/main/java/io/kestra/runner/postgres/PostgresQueue.java, jdbc-postgres/src/main/java/io/kestra/runner/postgres/PostgresWorkerTaskQueue.java, jdbc-postgres/src/main/resources/migrations/postgres/V14__queues_consumer_group.sql, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcQueue.java, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcQueueTest.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryQueue.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryWorkerTaskQueue.java
=> feat: introduce queue consumer group

ui/src/components/executions/Topology.vue, ui/src/components/flows/FlowEditor.vue, ui/src/components/flows/FlowRoot.vue, ui/src/components/inputs/EditorView.vue, ui/src/components/inputs/LowCodeEditor.vue
Remove vueflow from editor view so it can be used anywhere without the need of creating a whole editor.
Will also avoid nested editor in https://github.com/kestra-io/kestra/pull/1475
close #1458
=> Refactor(ui): EditorView topology refactoring

jdbc-mysql/src/main/java/io/kestra/repository/mysql/MysqlExecutionRepositoryService.java
=> fix(mysql): execution full text search was missing a field

build.gradle, core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java, core/src/test/java/io/kestra/core/docs/JsonSchemaGeneratorTest.java, core/src/test/java/io/kestra/core/runners/ExecutionServiceTest.java, core/src/test/java/io/kestra/core/runners/RestartTest.java, core/src/test/java/io/kestra/core/schedulers/SchedulerConditionTest.java, core/src/test/java/io/kestra/core/serializers/JacksonMapperTest.java, core/src/test/java/io/kestra/core/tasks/AbstractBashTest.java, core/src/test/java/io/kestra/core/tasks/DockerBashTest.java, core/src/test/java/io/kestra/core/tasks/NodeTest.java, core/src/test/java/io/kestra/core/tasks/flows/PauseTest.java, jdbc-h2/src/test/java/io/kestra/runner/h2/H2FlowListenersTest.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> chore(test): remove gradle retry and add unit retry for flaky test

core/src/main/java/io/kestra/core/serializers/YamlFlowParser.java, core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java, core/src/test/resources/flows/invalids/duplicate-key.yaml
=> fix(core): Raise duplicate key error

core/src/main/resources/docs/task.hbs, core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java
close [#1530](https://github.com/kestra-io/kestra/issues/1530)
=> fix(core): bad align in doc metrics

ui/src/components/executions/Kill.vue
Fixes #1303
The new kill button now looks like this (consistent with the replay and the future resume buttons)
=> fix: make the Kill button a button not a status

.github/ISSUE_TEMPLATE/blueprint.yml
Not sure whether this needs a separate label but it seems useful to potentially create a dedicated project board or auto-assign me or Ben to these issues
=> An issue template to allow community contributions to Blueprints

core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java, core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java
=> fix(core): remove definitions from the Task class

ui/src/components/Tabs.vue, ui/src/components/home/Home.vue
=> fix(ui): Hide chart if no executions yet in flow page

core/src/main/java/io/kestra/core/utils/RetryUtils.java
Some profiles shows up to 20% allocation and 10% cpu are spent in this method!
=> fix(core): lazy load thread stack trace as it's very costly

ui/src/components/flows/blueprints/BlueprintDetail.vue, ui/src/components/layout/TopNavBar.vue, ui/src/styles/layout/element-plus-overload.scss
closes #1511 (other changes are included in feat/blueprint-tabs)
=> fix(ui): Breadcrumb on Blueprints page

ui/src/components/onboarding/VueTour.vue, ui/src/translations.json
=> feat(ui): Updated guided tour flow

ui/src/components/logs/LogsWrapper.vue
=> fix(ui): reverse logs in flow page

ui/src/components/graph/TreeTaskNode.vue
=> fix(ui): Now display longest task in topo duration

ui/src/components/logs/LogList.vue
=> fix(ui): faster log display

ui/src/components/flows/FlowRun.vue, ui/src/components/flows/TriggerFlow.vue, ui/src/components/labels/LabelFilter.vue, ui/src/stores/executions.js, ui/src/translations.json
=> feat(ui): Add labels to new execution

ui/src/components/executions/Logs.vue, ui/src/components/logs/LogList.vue
=> fix(ui): Logs in gantt display correctly

ui/src/components/logs/LogList.vue, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> fix(ui): swap arrow icon in loglist

ui/src/components/flows/TaskEditor.vue
=> fix(ui): Update whole taskObject in TaskEditor

ui/src/utils/yamlUtils.js
=> fix(ui): show documentation correctly when cursor is at end of editor

core/src/main/java/io/kestra/core/models/conditions/types/MultipleCondition.java
link to : https://github.com/kestra-io/kestra.io/pull/332
=> fix(doc): multiple condition example

core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/main/java/io/kestra/core/validations/ValidationFactory.java, core/src/test/java/io/kestra/core/validations/FlowValidationTest.java, core/src/test/resources/flows/invalids/recursive-flow.yaml
=> fix(ui): prevent recursive flow calls

jdbc-postgres/src/main/java/io/kestra/runner/postgres/PostgresQueue.java
There is no way to force Postgres to use an index, and multiple tries in different indexes did not shows up performance improvement.
What we can do is, for this query, as Postgres to no do any sequential scan, effectively forcing it to use the index.
On simple benchmarking, it shows a small performance gain.
The test was:
- sending 50k execution of a one-task flow
- waiting for al executions to end
With seqscan=on (default on Postgres): 1909s to start 50k executions and 35mn to end them.
With seqscan=off: 1603s to start 50k executions and 20mn to end them.
Idle query performance seems to be slightly improved for he Executor (100ms with seqscan and 70ms without) and greatly with the Scheduler (248ms with seqscan and 17ms without). But these idle queries performance must be taken with care …
=> feat: disable seqscan on Postgres

.github/workflows/main.yml, build.gradle, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> chore: build JavaDoc on PR

ui/src/components/inputs/EditorView.vue
=> fix(ui): Unsaved popup does not show after saving

cli/src/main/resources/application.yml, webserver/src/main/java/io/kestra/webserver/filter/AuthenticationFilter.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java, webserver/src/test/java/io/kestra/webserver/filter/AuthenticationFilterTest.java, webserver/src/test/resources/application.yml
=> feat(webserver): add basic authentication

core/src/main/java/io/kestra/core/tasks/storages/LocalFiles.java, core/src/test/java/io/kestra/core/tasks/storages/LocalFilesTest.java, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java
Things that still needs to be discussed:
- naming of the attributes (inputs/outputs)
- split on two tasks like SetLocaFiles and GetLocalFiles
- if we should evolve to more complex properties for ex to handle file attributes (note that it can be done in another properties that allow to change attributes of any file withing the file system).
close #1478
=> feat: LocalFiles task

ui/src/components/inputs/Editor.vue, ui/src/components/inputs/MonacoEditor.vue, ui/src/components/settings/Settings.vue, ui/src/translations.json
close #1218
close https://github.com/kestra-io/kestra/issues/1654
=> feat(): Allow to change fontSize & fontFamily in editor from Settings

core/src/main/resources/docs/task.hbs
MD inline code handles the chars.
=> Render chars instead of entities

core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java, core/src/main/java/io/kestra/core/tasks/flows/WorkingDirectory.java, core/src/test/java/io/kestra/core/tasks/flows/WorkingDirectoryTest.java, core/src/test/resources/flows/valids/working-directory-cache.yml, storage-local/src/main/java/io/kestra/storage/local/LocalStorage.java, storage-local/src/test/java/io/kestra/storage/local/LocalStorageTest.java
close [#1275](https://github.com/kestra-io/kestra/issues/1275)
=> feat: allow to cache contents inside the working directory

build.gradle
Link to https://github.com/kestra-io/plugin-crypto/pull/30
=> fix(): force bouncycastle version for crypto plugin compatibility

core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java, core/src/test/resources/flows/valids/webhook-dynamic-key.yaml, webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
close [#1856](https://github.com/kestra-io/kestra/issues/1856)
=> feat: make the webhook key dynamic

cli/src/main/java/io/kestra/cli/commands/servers/ExecutorCommand.java, cli/src/main/java/io/kestra/cli/commands/servers/StandAloneCommand.java, core/src/main/java/io/kestra/core/services/SkipExecutionService.java, core/src/test/java/io/kestra/core/runners/SkipExecutionCaseTest.java, core/src/test/java/io/kestra/core/services/SkipExecutionServiceTest.java, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java, runner-memory/src/main/java/io/kestra/runner/memory/MemoryExecutor.java, runner-memory/src/test/java/io/kestra/runner/memory/MemorySkipExecutionTest.java
close [#767](https://github.com/kestra-io/kestra/issues/767)
=> feat: allow to skip an execution

core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java, core/src/test/java/io/kestra/core/models/triggers/types/ScheduleTest.java
=> feat: add flow inputs with default values in the Schedule execution

ui/src/components/inputs/Editor.vue, ui/src/components/onboarding/VueTour.vue, ui/src/translations.json
closes https://github.com/kestra-io/kestra/issues/1936
=> (fix) Onboarding Guide

ui/src/translations.json
Still some things can be further enhanced 
also @brian-mulier-p can you help me fix this issue? the window disappears to the bottom left corner on step 11 and step 12 after saving the flow in step 10
=> feat(ui): even better wording in the guided tour

core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java, core/src/test/java/io/kestra/core/validations/ScheduleTest.java
=> fix: Schedule trigger cannot have an interval

core/src/main/java/io/kestra/core/serializers/FileSerde.java, core/src/test/java/io/kestra/core/serializers/FileSerdeTest.java, webserver/src/main/java/io/kestra/webserver/utils/filepreview/IonFileRender.java
Fixes https://github.com/kestra-io/kestra-ee/issues/385
=> fix(core, webserver): ION file preview must limit the number of lines

ui/src/components/executions/VarValue.vue
close [#kestra-ee/425](https://github.com/kestra-io/kestra-ee/issues/425)
=> fix(): fix file download URL

webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
=> fix(): remove useless redirection

core/src/main/java/io/kestra/core/runners/Worker.java
Following some discussion on Slack improve Worker log messages to be less confusing.
=> Feat(core): improve worker logs

cli/src/main/java/io/kestra/cli/commands/flows/FlowTestCommand.java, core/src/main/java/io/kestra/core/models/flows/Input.java, core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java, core/src/main/java/io/kestra/core/runners/RunnerUtils.java, core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/test/java/io/kestra/core/runners/InputsTest.java, core/src/test/java/io/kestra/core/runners/RunContextTest.java, ui/src/components/flows/FlowRun.vue, webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
=> fix(core): allow typed inputs to support bool

ui/src/components/flows/FlowRun.vue
Now this will keep undefined if no default is set and if user does not touch the switch to set any value for the boolean inputs.
close #1904
=> fix(ui): Avoid setting a default value if none is set to boolean inputs

jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java
Some flaky test handling, not all but at least some I stumble upon recently.
=> fix: flaky tests

ui/src/components/executions/Executions.vue, ui/src/components/logs/LogsWrapper.vue
=> fix(ui): remove default end date

ui/src/components/flows/FlowRun.vue
A follow-up to #2193.
* Handles cases with no execution labels correctly.
* The prefill button can be used for prefilling the labels even w/o inputs.
=> Improve the execution prefill

core/src/main/java/io/kestra/core/tasks/flows/Pause.java
closes https://github.com/kestra-io/kestra/issues/2255
=> fix(docs): Pause task enhancements

core/src/main/java/io/kestra/core/runners/Worker.java
This avoid CREATED -> RUNNING -> KILLING when we know we will kill the task.
=> feat: set to killed before set it to running

core/src/main/java/io/kestra/core/runners/FlowableUtils.java
=> fix(core): Dag task with error handler now terminate correctly

ui/package-lock.json, ui/package.json
=> chore(ui): update ui-libs version

core/src/main/java/io/kestra/core/models/triggers/types/Webhook.java, core/src/test/resources/flows/valids/webhook-with-condition.yaml, webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java, webserver/src/test/java/io/kestra/webserver/controllers/ExecutionControllerTest.java
@anna-geller, I took the occasion to slightly improve the documentation, can you have a look?
close #2267
=> feat(core,webserver): support conditions on webhooks

webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
Share webhook code so it can be used by the EE which currently duplicates it
=> fix(webserver): share webhook code for EE

core/src/main/java/io/kestra/core/storages/FileAttributes.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java, storage-local/src/main/java/io/kestra/storage/local/LocalFileAttributes.java, storage-local/src/main/java/io/kestra/storage/local/LocalStorage.java, storage-local/src/test/java/io/kestra/storage/local/LocalStorageTest.java, webserver/src/main/java/io/kestra/webserver/controllers/NamespaceFileController.java, webserver/src/test/java/io/kestra/webserver/controllers/NamespaceFileControllerTest.java
Add endpoint and method to storage interface to allow the new file editor to create/move/delete and edit files and directories in a new storage prefix.
=> feat(core,webserver): multi file editor

core/src/main/java/io/kestra/core/runners/FlowListeners.java, core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java, core/src/main/java/io/kestra/core/services/AbstractFlowTriggerService.java
=> feat: don't filter flow with exception on the FlowListeners

README.md
command "docker-compose up" is for v1 compose, not working for now compose v2 (error "unsupported config options for service 'kestra') "docker compose up" still works without errors
---
---
=> docker-compose change to docker compose in readme

core/src/main/java/io/kestra/core/tasks/flows/Dag.java, core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/main/java/io/kestra/core/tasks/flows/If.java, core/src/main/java/io/kestra/core/tasks/flows/Parallel.java, core/src/main/java/io/kestra/core/tasks/flows/Sequential.java, core/src/main/java/io/kestra/core/tasks/flows/Switch.java, core/src/main/java/io/kestra/core/tasks/log/Fetch.java, core/src/main/java/io/kestra/core/tasks/log/Log.java
Docs only.
The log task triggered this 😆
=> fix(docs): Fix documentation of some core tasks

cli/src/main/java/io/kestra/cli/AbstractApiCommand.java, cli/src/main/java/io/kestra/cli/AbstractValidateCommand.java, cli/src/main/java/io/kestra/cli/commands/flows/FlowExportCommand.java, cli/src/main/java/io/kestra/cli/commands/flows/namespaces/FlowNamespaceUpdateCommand.java, cli/src/main/java/io/kestra/cli/commands/templates/TemplateExportCommand.java, cli/src/main/java/io/kestra/cli/commands/templates/namespaces/TemplateNamespaceUpdateCommand.java
Fixes https://github.com/kestra-io/kestra-ee/issues/512
=> feat(cli): add optional tenantId for flow and template commands

ui/package-lock.json, ui/src/components/settings/BasicSettings.vue, ui/src/override/components/settings/Settings.vue, ui/src/routes/routes.js, ui/src/utils/filters.js
link to https://github.com/kestra-io/kestra-ee/pull/461
=> feat(ui): make settings a components to align EE changes

ui/src/components/inputs/LowCodeEditor.vue
=> fix(ui): provide section to task-edit component

core/src/main/java/io/kestra/core/services/StorageService.java, core/src/main/java/io/kestra/core/storages/StorageInterface.java, core/src/main/java/io/kestra/core/storages/StorageSplitInterface.java, core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java, core/src/main/java/io/kestra/core/tasks/storages/Split.java, core/src/test/java/io/kestra/core/tasks/flows/ForEachItemCaseTest.java, core/src/test/resources/flows/valids/for-each-item-no-wait.yaml, core/src/test/resources/flows/valids/for-each-item.yaml
and refactor Split to use a common service
=> feat(core): add batch properties to ForEachItem

ui/src/components/flows/FlowRoot.vue
=> fix(ui):dependencies count subtract one

ui/src/utils/state.js
=> feat(ui):add a CANCELED state

ui/src/components/namespace/Editor.vue
Only redirect if tutorial has been done or skip (as the files editor now allow flow creation)
=> feat(ui): Select first namespace by default in editor, if none exist and tutorial not done redirect to flow creation

core/src/main/java/io/kestra/core/models/executions/TaskRun.java, core/src/main/java/io/kestra/core/models/tasks/Task.java, core/src/main/java/io/kestra/core/models/triggers/AbstractTrigger.java, core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/RunContextLogger.java, core/src/test/java/io/kestra/core/runners/ExecutionServiceTest.java, core/src/test/java/io/kestra/core/runners/RunContextTest.java, core/src/test/java/io/kestra/core/serializers/YamlFlowParserTest.java, core/src/test/resources/flows/valids/logs.yaml, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcRunnerTest.java, webserver/src/test/java/io/kestra/webserver/controllers/PluginControllerTest.java
Fixes #2245
I wonder if this is the good implementation choice here and if we should not provide an instance-wide setting and re-evaluate our default to TRACE.
=> feat(core): allow to configure min log level for tasks and triggers

core/src/main/java/io/kestra/core/models/tasks/NamespaceFiles.java, core/src/main/java/io/kestra/core/models/tasks/NamespaceFilesInterface.java, core/src/main/java/io/kestra/core/runners/NamespaceFilesService.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/tasks/flows/WorkingDirectory.java, core/src/test/java/io/kestra/core/runners/NamespaceFilesServiceTest.java, core/src/test/java/io/kestra/core/tasks/flows/WorkingDirectoryTest.java, core/src/test/java/io/kestra/core/tasks/test/Read.java, core/src/test/resources/flows/valids/working-directory-namespace-files.yaml
=> feat(core): add NamespaceFiles props on WorkingDirectory

ui/src/components/settings/BasicSettings.vue, ui/src/translations.json, ui/src/utils/toast.js
=> feat(ui):Adjust the toast when changing anything in Settings

build.gradle, core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/RunContextCache.java, core/src/test/java/io/kestra/core/tasks/flows/VariablesTest.java
=> feat(core): improve performance on runContext caching some fixed variable

core/src/main/java/io/kestra/core/storages/StorageSplitInterface.java, core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java
This PR improves task documentation + gives a full example
closes https://github.com/kestra-io/kestra/issues/2519
=> doc: clarify ForEachItem properties and provide a full example

core/src/main/java/io/kestra/core/runners/ExecutableUtils.java, core/src/test/java/io/kestra/core/tasks/flows/ForEachItemCaseTest.java
=> fix(core): add taskrun attemp when ending the ForEachItem task run

core/src/main/java/io/kestra/core/runners/FlowableUtils.java, core/src/test/java/io/kestra/core/tasks/flows/EachParallelTest.java, core/src/test/resources/flows/valids/each-parallel-Integer.yml
=> Support integer values in EachParallel

ui/src/components/namespace/Editor.vue, ui/src/utils/constants.js
=> feat(): keep last selected namespace in files editor

core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java, ui/src/components/flows/tasks/Task.js, ui/src/components/flows/tasks/TaskAnyOf.vue, ui/src/components/flows/tasks/TaskObject.vue, ui/src/utils/init.js
close #1383
* See comment around code
=> fix(ui): Add form for anyOf type

ui/src/styles/layout/element-plus-overload.scss
=> fix(): apply class correctly

jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java, jdbc/src/test/java/io/kestra/jdbc/runner/JdbcHeartbeatTest.java
=> feat(jdbc): skip worker task running resubmission for skipped execution

ui/src/stores/worker.js
Fixes https://github.com/kestra-io/kestra-ee/issues/589
=> fix(ui): the workers API is global to all tenants

core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/VariableRenderer.java, core/src/test/java/io/kestra/core/models/hierarchies/FlowGraphTest.java, core/src/test/java/io/kestra/core/runners/RunContextTest.java, core/src/test/java/io/kestra/core/runners/pebble/PebbleVariableRendererTest.java, core/src/test/resources/flows/templates/with-template.yaml, core/src/test/resources/flows/valids/return.yaml
=> fix(): prerender variables

ui/src/components/executions/Executions.vue
=> fix(ui): use correct key when change display columns on execution list

core/src/main/java/io/kestra/core/models/executions/Execution.java
May fix https://github.com/kestra-io/kestra-ee/issues/616
=> fix(core): possible NPE on execution.findChilds()

ui/src/override/components/LeftMenu.vue
Added shallowRef on the way
link to https://github.com/kestra-io/kestra-ee/pull/613
close #2580
=> fix(ui): avoid admin menu blinking

core/src/main/java/io/kestra/core/services/ExecutionService.java, ui/src/components/executions/ChangeStatus.vue
The CREATED task was not allowed to change status, this PR allow it.
Fixes #1305
=> feat(ui): allow to change the status of a CREATED task

core/src/main/resources/docs/task.hbs
=> fix(core): add 'deprecated' to the task front matter title

core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/test/java/io/kestra/core/runners/RunContextTest.java
This allows protection against path traversal issue.
=> feat(core): provide a method in the run context to safely resolve a path

core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/main/java/io/kestra/core/tasks/flows/Subflow.java, core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java, core/src/test/java/io/kestra/core/models/hierarchies/FlowGraphTest.java, core/src/test/java/io/kestra/core/services/FlowTopologyServiceTest.java, core/src/test/java/io/kestra/core/tasks/flows/FlowCaseTest.java, core/src/test/resources/flows/invalids/recursive-flow.yaml, core/src/test/resources/flows/valids/each-parallel-subflow-notfound.yml, core/src/test/resources/flows/valids/task-allow-failure-executable-flow.yml, core/src/test/resources/flows/valids/task-flow.yaml, jdbc/src/test/java/io/kestra/jdbc/runner/AbstractWorkerTaskExecutionTest.java, ui/package-lock.json, ui/package.json, webserver/src/test/java/io/kestra/webserver/controllers/NamespaceFileControllerTest.java, webserver/src/test/resources/__files/blueprint-flow.yaml
Fixes [#2604](https://github.com/kestra-io/kestra/issues/2604)
=> feat(core): rename the Flow task to Subflow

core/src/main/java/io/kestra/core/models/triggers/types/Flow.java, core/src/test/java/io/kestra/core/models/triggers/types/FlowTest.java
Fixes https://github.com/kestra-io/kestra-ee/issues/680
=> fix(core): add the tenant in the Flow trigger

core/src/main/java/io/kestra/core/models/conditions/types/DateTimeBetweenCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/DayWeekCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/DayWeekInMonthCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/ExecutionFlowCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/ExecutionNamespaceCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/ExecutionStatusCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/FlowCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/FlowNamespaceCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/HasRetryAttemptCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/MultipleCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/NotCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/OrCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/PublicHolidayCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/TimeBetweenCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/VariableCondition.java, core/src/main/java/io/kestra/core/models/conditions/types/WeekendCondition.java
Corrected the docs under conditions
=> fix(docs): corrected the docs under conditions

core/src/main/java/io/kestra/core/tasks/debugs/Echo.java, core/src/main/java/io/kestra/core/tasks/debugs/Return.java, core/src/main/java/io/kestra/core/tasks/executions/Counts.java, core/src/main/java/io/kestra/core/tasks/executions/Fail.java, core/src/main/java/io/kestra/core/tasks/flows/AllowFailure.java, core/src/main/java/io/kestra/core/tasks/flows/Dag.java, core/src/main/java/io/kestra/core/tasks/flows/EachParallel.java, core/src/main/java/io/kestra/core/tasks/flows/EachSequential.java, core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java, core/src/main/java/io/kestra/core/tasks/flows/If.java, core/src/main/java/io/kestra/core/tasks/flows/Parallel.java, core/src/main/java/io/kestra/core/tasks/flows/Sequential.java
Some of the examples were mentioned as tasks. Converted them to flows for easy understanding.
=> fix(docs): corrected the docs on multiple flows

core/src/main/java/io/kestra/core/tasks/debugs/Echo.java, core/src/main/java/io/kestra/core/tasks/debugs/Return.java, core/src/main/java/io/kestra/core/tasks/executions/Counts.java, core/src/main/java/io/kestra/core/tasks/executions/Fail.java, core/src/main/java/io/kestra/core/tasks/flows/AllowFailure.java, core/src/main/java/io/kestra/core/tasks/flows/Dag.java, core/src/main/java/io/kestra/core/tasks/flows/EachParallel.java, core/src/main/java/io/kestra/core/tasks/flows/EachSequential.java, core/src/main/java/io/kestra/core/tasks/flows/Flow.java, core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java, core/src/main/java/io/kestra/core/tasks/flows/If.java, core/src/main/java/io/kestra/core/tasks/flows/Parallel.java, core/src/main/java/io/kestra/core/tasks/flows/Sequential.java
=> Revert "fix(docs): corrected the docs on multiple flows"

ui/src/translations.json
fixes some wording in UI display
=> fix: wording in translations

core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java
Fixes https://github.com/kestra-io/kestra-ee/issues/770
=> fix(core): add the tenantId at trigger creation

core/src/main/java/io/kestra/core/utils/AuthUtils.java, webserver/src/main/java/io/kestra/webserver/controllers/MiscController.java, webserver/src/main/java/io/kestra/webserver/filter/AuthenticationFilter.java, webserver/src/main/java/io/kestra/webserver/listeners/OssAuthListener.java, webserver/src/main/java/io/kestra/webserver/models/events/Event.java, webserver/src/main/java/io/kestra/webserver/models/events/OssAuthEvent.java, webserver/src/main/java/io/kestra/webserver/services/BasicAuthService.java, webserver/src/test/java/io/kestra/webserver/controllers/MiscControllerSecuredTest.java, webserver/src/test/java/io/kestra/webserver/controllers/MiscControllerTest.java, webserver/src/test/java/io/kestra/webserver/filter/AuthenticationFilterTest.java, webserver/src/test/java/io/kestra/webserver/services/BasicAuthServiceTest.java, webserver/src/test/resources/application-test.yml
=> Basic authentication saved in Repository

core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/storages/StorageContext.java, core/src/main/java/io/kestra/core/utils/Hashing.java, core/src/test/java/io/kestra/core/storages/StorageContextTest.java, core/src/test/java/io/kestra/core/utils/HashingTest.java
=> fix(core): use consistent hashing function for storage prefix (#2934)

.github/workflows/main.yml
=> feat(docker): introduce Solace plugin

core/src/main/java/io/kestra/core/storages/InternalStorage.java, core/src/test/java/io/kestra/core/storages/InternalStorageTest.java
This commit fixes a regression from commit 9e1b660
---
---
=> fix(core): taskRunValue should be optional for task state file

ui/src/components/logs/TaskRunDetails.vue
=> fix(ui): fix duplicated subflow logs (#2641)

core/src/main/java/io/kestra/core/repositories/ExecutionRepositoryInterface.java, core/src/main/java/io/kestra/core/services/ExecutionService.java, core/src/test/java/io/kestra/core/repositories/AbstractExecutionRepositoryTest.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcExecutionRepository.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryExecutionRepository.java, ui/src/components/executions/Executions.vue, ui/src/components/taskruns/TaskRuns.vue, ui/src/translations.json, webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java, webserver/src/main/java/io/kestra/webserver/controllers/TaskRunController.java
=> feat(core): add a filter for child executions

core/src/main/java/io/kestra/core/models/triggers/AbstractTrigger.java, core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/RunContextLogger.java, core/src/main/java/io/kestra/core/runners/pebble/functions/SecretFunction.java, core/src/test/java/io/kestra/core/runners/RunContextLoggerTest.java, core/src/test/java/io/kestra/core/secret/SecretFunctionTest.java, core/src/test/resources/flows/valids/secrets.yaml
=> feat(core): automaticaly hide secret on log

core/src/main/java/io/kestra/core/runners/ExecutionQueued.java, core/src/main/java/io/kestra/core/runners/ExecutionRunning.java, core/src/main/java/io/kestra/core/runners/Executor.java, core/src/main/java/io/kestra/core/runners/ExecutorService.java, core/src/main/java/io/kestra/core/runners/RunnerUtils.java, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
Changes needed for the related fix on the Kafka runner.
=> fix(core): implement concurrency without ExecutionQueued

cli/src/main/resources/application.yml, core/src/main/java/io/kestra/core/tasks/flows/Subflow.java, core/src/test/resources/application-test.yml
=> chore(core): rename config property (#2953)

core/src/main/java/io/kestra/core/tasks/flows/EachSequential.java
document the parent.taskrun.value
=> docs: add example for accessing parent taskrun value

core/src/main/java/io/kestra/core/models/executions/LogEntry.java, core/src/main/java/io/kestra/core/queues/QueueService.java, core/src/main/java/io/kestra/core/repositories/LogRepositoryInterface.java, core/src/main/java/io/kestra/core/runners/RunContextLogger.java, core/src/test/java/io/kestra/core/repositories/AbstractLogRepositoryTest.java, jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcLogRepository.java, repository-memory/src/main/java/io/kestra/repository/memory/MemoryLogRepository.java, webserver/src/main/java/io/kestra/webserver/controllers/LogController.java, webserver/src/test/java/io/kestra/webserver/controllers/LogControllerTest.java
=> feat(*): remove logId and delete log by query

ui/src/components/flows/FlowTriggers.vue, ui/src/components/flows/TriggerAvatar.vue, ui/src/components/flows/TriggerVars.vue
Trigger description was not correctly rendered as Markdown at various places.
=> fix(ui): render trigger description as Markdown

core/src/main/java/io/kestra/core/utils/Hashing.java
This commit adds required utilities for further improvements.
=> chore(core): add required utility methods

ui/src/components/flows/FlowCreate.vue, ui/src/components/inputs/EditorView.vue
=> fix(ui): allow to save the default flow without any modification

core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java
So they are re-evaluated each second
=> fix(core): polling trigger didn't update their next evaluation date

core/src/main/java/io/kestra/core/runners/ExecutorService.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java, core/src/main/java/io/kestra/core/services/LogService.java, core/src/test/java/io/kestra/core/services/LogServiceTest.java, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java
Fixes https://github.com/kestra-io/kestra-ee/issues/863
=> Feat(core, jdbc): refactor execution loggind and add the tenant

ui/src/components/flows/FlowTriggers.vue
close  https://github.com/kestra-io/kestra-ee/issues/860
=> fix(): only required one double click to execute action

core/src/main/java/io/kestra/core/models/triggers/Trigger.java, core/src/main/java/io/kestra/core/services/FlowService.java, webserver/src/main/java/io/kestra/webserver/controllers/TriggerController.java, webserver/src/test/java/io/kestra/webserver/controllers/TriggerControllerTest.java
=> fix(): correct next execution date when updating trigger from ui/source

ui/src/stores/flow.js
=> fix(ui): export flows

core/src/main/java/io/kestra/core/validations/validator/WorkerGroupValidator.java
Fixes https://github.com/kestra-io/kestra-ee/issues/882
=> fix(core): WorkerGroupValidator never validates on the Namespaces page

ui/src/components/executions/Executions.vue, ui/src/components/executions/SetLabels.vue
The dialog presented previously entered values.
---
1. Open _Set labels_ dialog
1. Input a value
1. Click _Close_
1. Open the dialog again
=> fix(ui): reset the set labels dialog

cli/src/main/resources/application.yml, core/src/main/java/io/kestra/core/models/triggers/types/Schedule.java, core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java, core/src/main/java/io/kestra/core/schedulers/DefaultScheduler.java, core/src/test/java/io/kestra/core/models/triggers/types/ScheduleTest.java, core/src/test/java/io/kestra/core/plugins/PluginConfigurationTest.java, core/src/test/java/io/kestra/core/schedulers/SchedulerScheduleTest.java, core/src/test/resources/application-test.yml, jdbc/src/main/java/io/kestra/jdbc/runner/JdbcScheduler.java, ui/src/translations.json
Fixes #2219
Allow to specify the behavior in case of missed schedules: recover all, recover last or recover none.
=> feat(core): Recover Missed Schedule

ui/src/components/executions/Executions.vue
Daily statistci was missing if no date or time range was present in the query string. Also remove duplicated filter.
Fixes https://github.com/kestra-io/kestra-ee/issues/894
=> fix(ui): missing executions page daily statistic

ui/src/App.vue
=> chore(ui): add a toast asking user to validate their instance security (#2583)

ui/src/components/inputs/SwitchView.vue
=> fix(ui): light mode selected editor button

ui/src/components/layout/Labels.vue
=> fix(ui): fix style of execution filter query labels (#3168)

ui/src/components/flows/FlowCreate.vue
to teach all concepts even if user skips the guided tour
=> New flow template

jdbc/src/main/java/io/kestra/jdbc/repository/AbstractJdbcFlowRepository.java
Fixes #2956
It can only be tested by having an old plugin in the classpath (for ex le plugin-fs version 0.12), in this case the server will start with an error log and flows that didn't use this plugin will work.
There will also be error in the UI each time the UI will try to access the flow that uses the old plugin but at least the server will not crash.
=> fix(jdbc): make the flow listener tolerant of plugin loader issue

core/src/main/java/io/kestra/core/models/flows/TaskDefault.java, core/src/main/java/io/kestra/core/validations/TaskDefaultValidation.java, core/src/main/java/io/kestra/core/validations/validator/TaskDefaultValidator.java, core/src/test/java/io/kestra/core/validations/TaskDefaultValidationTest.java
=> fix(core): validate task default

core/src/main/java/io/kestra/core/runners/VariableRenderer.java, core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java, core/src/test/java/io/kestra/core/runners/pebble/functions/RenderFunctionTest.java
=> fix(core): pebble render function must render boolean (#3218)

core/src/main/java/io/kestra/core/tasks/flows/ChildFlowInterface.java, core/src/main/java/io/kestra/core/tasks/flows/ForEachItem.java, core/src/main/java/io/kestra/core/tasks/flows/Subflow.java
Link to https://github.com/kestra-io/kestra-ee/pull/975
closes #3210
=> fix(core): create dependency between forEachItem task and subflow

ui/package-lock.json, ui/src/components/Tabs.vue, ui/src/components/executions/Executions.vue, ui/src/components/executions/MetricsTable.vue, ui/src/components/executions/Restart.vue, ui/src/components/executions/date-select/DateFilter.vue, ui/src/components/flows/FlowMetrics.vue, ui/src/components/flows/FlowRun.vue, ui/src/components/flows/FlowTriggers.vue, ui/src/components/flows/TriggerFlow.vue, ui/src/components/flows/blueprints/BlueprintDetail.vue, ui/src/components/inputs/Editor.vue, ui/src/components/inputs/EditorButtons.vue, ui/src/components/inputs/EditorView.vue, ui/src/components/layout/Labels.vue, ui/src/components/layout/RefreshButton.vue, ui/src/components/logs/LogsWrapper.vue, ui/src/override/components/flows/blueprints/BlueprintsBrowser.vue, ui/src/routes/routes.js, ui/src/utils/charts.js
This is an attempt to resolve multiple issues triggering dev warnings. Flood of Vue warnings made the console hard to work with.
Feel free to use a better approach for issues resolved by adding `v-bind="$attrs"`.
=> chore(ui): fix various UI dev warnings

core/src/main/java/io/kestra/core/tasks/storages/Delete.java, core/src/main/java/io/kestra/core/tasks/storages/Reverse.java, core/src/main/java/io/kestra/core/tasks/storages/Size.java, core/src/main/java/io/kestra/core/tasks/storages/Split.java
=> feat(core): make the 'from' property of storage tasks mandatory

ui/src/components/inputs/EditorView.vue, ui/src/translations/en.json, ui/src/translations/fr.json
=> feat(): allow to override existing flow

core/src/main/java/io/kestra/core/docs/DocumentationGenerator.java, core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java, core/src/main/java/io/kestra/core/docs/Plugin.java, core/src/main/java/io/kestra/core/models/script/AbstractLogConsumer.java, core/src/main/java/io/kestra/core/models/script/RunnerResult.java, core/src/main/java/io/kestra/core/models/script/ScriptCommands.java, core/src/main/java/io/kestra/core/models/script/ScriptException.java, core/src/main/java/io/kestra/core/models/script/ScriptRunner.java, core/src/main/java/io/kestra/core/models/script/ScriptService.java, core/src/main/java/io/kestra/core/models/script/types/ProcessScriptRunner.java, core/src/main/java/io/kestra/core/plugins/PluginRegistry.java, core/src/main/java/io/kestra/core/plugins/PluginScanner.java, core/src/main/java/io/kestra/core/plugins/RegisteredPlugin.java, core/src/main/java/io/kestra/core/runners/RunContext.java, core/src/main/java/io/kestra/core/runners/Worker.java, core/src/main/java/io/kestra/core/utils/ListUtils.java, core/src/main/java/io/kestra/core/utils/MapUtils.java, core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java, core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java, core/src/test/java/io/kestra/core/models/script/AbstractScriptRunnerTest.java, core/src/test/java/io/kestra/core/models/script/ScriptServiceTest.java, core/src/test/java/io/kestra/core/models/script/types/ProcessScriptRunnerTest.java, core/src/test/java/io/kestra/core/utils/ListUtilsTest.java, core/src/test/java/io/kestra/core/utils/MapUtilsTest.java
Provides a new kind of plugins: Script Runners
=> feat: Script runners as plugins

core/src/main/resources/logback/text.xml
=> feat: hide JooQ log about not supported DB version

core/src/main/java/io/kestra/core/models/script/ScriptService.java, core/src/test/java/io/kestra/core/models/script/ScriptServiceTest.java
This avoid duplicating the code in multiple plugins
=> feat(core): ScriptService.labels() and ScriptService.jobName()

core/src/main/java/io/kestra/core/services/CollectorService.java, core/src/test/java/io/kestra/core/services/CollectorServiceTest.java
=> fix(core): fix stats webserver (#3408)

ui/src/components/executions/Executions.vue, ui/src/stores/executions.js, ui/src/translations/en.json, ui/src/translations/fr.json, webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java
=> feat(ui): add message to warn for deleting running exec (#2651)

ui/src/components/executions/Executions.vue, ui/src/components/executions/Overview.vue, ui/src/components/executions/Restart.vue, ui/src/components/logs/LogsWrapper.vue
Multiple margins were off. For example:
=> fix(ui): correct various margins

ui/src/components/plugins/Plugin.vue, ui/src/components/plugins/PluginHome.vue, ui/src/components/plugins/Toc.vue, ui/src/stores/plugins.js, ui/src/styles/layout/element-plus-overload.scss, ui/src/translations/en.json, ui/src/translations/fr.json, webserver/src/main/java/io/kestra/webserver/controllers/PluginController.java
=> feat(ui): revamp plugin documentation
